- feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
- feature/sessions/src/commonMain/composeResources/values/strings.xml
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailSummaryCard.kt
- close #221 
- The title was previously hard-coded and did not used the string resources.
- I added a string key that supports both Japanese and English to the `:feature:session` module and implemented the key.
Before | After
:--: | :--:
> Support English on the detail screen title

- feature/sessions/src/commonMain/composeResources/values/strings.xml
- close #209 
- "Readmore" on the session details screen updated to "More" when the app language is English
Before | After
:--: | :--:
> Fix "Readmore" text to "More" in session detail screen

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/FixedAccentColors.kt
- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Theme.kt
- Added fixed colors.
- Not applied to each screen.
- This is required before #227 .
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=53699-35660&t=gQTFzGMHPcAZemBX-4
- sample: https://github.com/androidx/androidx/blob/88a2d443f349b046617d750457d438dd8637cc4e/compose/material3/material3/samples/src/main/java/androidx/compose/material3/samples/ColorSchemeSamples.kt#L34
Before | After
:--: | :--:
Before | After
:--: | :--:
> Added fixed colors

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailHeadline.kt
- close #220 
- Centered Speaker names in session details
- 
Before | After
:--: | :--:
> Session detail screen: Speaker name not center-aligned next to icon

- app-ios/Sources/App/RootReducer.swift
- app-ios/Sources/App/RootView.swift
- app-ios/Sources/TimetableDetailFeature/TimetableDetailView.swift
- Set tab bar color to black
- Set navigation bar color to black
- Add logic to back to root stack when tapping same tab
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/7c774542-ef38-49d5-b607-8534ba8c8986" width="300" >
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/5a803e30-7410-4db2-9227-e1e75bec6c6f" width="300" >
> Fix minor bug in tab bar and navigation bar

- feature/about/src/commonMain/composeResources/values-ja/strings.xml
- feature/about/src/commonMain/composeResources/values/strings.xml
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt
- close #223 
- Implement the app bar "About DroidKaigi" in the About list screen using `TopAppBar`
- figma https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54982-75342&t=k4TShQboqq07iWl6-0
Before | After (Japanase) | After (English)
According to [this figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55725-8670&t=htgSgF3wWucKlsEr-0), the `"About Droidkaigi"` text in the App Bar seems to be fixed in the center when scrolling the screen.
Should this feature be resolved in this PR? Should it be separated into a different issue?
> Implement the app bar "About DroidKaigi" in the About list screen

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/AboutItem.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutDroidKaigiDetailSummaryCard.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutDroidKaigiDetailSummaryCardRow.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutDroidKaigiDetail.kt
- close #205
- Added a 'View Map' text button to the About screen."
- [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54985-75942&t=e1CZJMlo119t4tkU-4)
Before | After
:--: | :--:
Before | After
:--: | :--:
None | <video src="https://github.com/user-attachments/assets/a0b8c1bb-73dd-4f9f-b11e-c3f3514d37e3" width="300" >
> Added a 'View Map' text button to the About screen."

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Theme.kt
- Support for color contrast features on Android 14 and later.
- The colors in the generated ColorScheme support contrast switching, but the room color and fixed color are not supported and will not switch.
- https://m3.material.io/styles/color/system/how-the-system-works#0207ef40-7f0d-4da8-9280-f062aa6b3e04
Before | After Default | Medium Contrast | High Contrast
:--: | :--: | :--: | :--:
The color of FAB and Outlined that use ColorScheme will change depending on the device's contrast settings.
Before | After
:--: | :--:
> Support color constrast theming

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- close https://github.com/DroidKaigi/conference-app-2024/issues/224
- Changed the shape of speaker icons in the timeline grid from rounded rectangle to circles.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Changed the shape of speaker icons in the timeline grid from rounded rectangle to circles

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- close #207 
- Previously, the timetable icon was fixed by the `Grid3x3` icon. 
- Now, each icon is determined by the `timetableUiType` state.
- When displaying the timetable in grid type, the icon is shown as `Icons.Default.ViewTimeline`.
- When displaying the timetable in list type, the icon is shown as `Icons.Default.GridView`.
- [Related Figma link](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54876-39860&t=2ihtMr09UnG5zVpA-4)
Before | Grid | Timeline
(To check cross fade animation.)
https://github.com/user-attachments/assets/bf748254-b963-4c19-b97d-84f0147258d6
> Change time table icon by state

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- close #226 
- Adjusted padding to increase spacing between bottom navigation items
- 
Before | After
:--: | :--:
- I'm concerned about the bottom navigation interfering with the system navigation. (Device: Pixel 7)
> Adjusted padding to increase spacing between bottom navigation items

- feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
- feature/sessions/src/commonMain/composeResources/values/strings.xml
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailContent.kt
- close #213 
- Changed the details screen for special content such as Welcome Talk and Lunch Break to display the appropriate wording.
- nothing
Before | After
:--: | :--:
> Display appropriate information for Welcome Talk and Lunch Break in Timetable detail screen

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutCredits.kt
- nothing
- The sponsor title on the About page was written as "staff," so I have corrected it.
- nothing
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fixed sponsor wording on About page

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenPresenter.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableTime.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- #201 
- The times are displayed on the left side of the existing timetable list.
- To make time data easier to consume, I changed this type to `Pair<String, String>`.
- I Added `@Composable fun TimetableTime()` to display timetables.
- Since many columns and rows are overlapping, I modified all but the topmost `LazyColumn` to `Column` of `TimetableList`.
- There was no design issue, So I just slightly modified the spacing between some of the views in compliance with Figma(except for Font).
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add time display to the left side of the timetable

- feature/eventmap/src/commonMain/composeResources/values-ja/strings.xml
- feature/eventmap/src/commonMain/composeResources/values/strings.xml
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
- Fixed "イベントマップ" text to use string resource since it is hard-coded.
- Supported in Japanese and English.
Before | After (Japanese) | After (English)
> "EventMap" text uses string resource

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemCard.kt
- close #214
- Change transition area cover entire card.
- nothing
nothing
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/5b487648-7ced-425e-a322-3b115d18b9a6" width="300" > | <video src="https://github.com/user-attachments/assets/7715c201-020c-4694-9c27-32ff7703e56e" width="300" >
> Change transition area to cover entire card

- app-android/src/test/java/io/github/droidkaigi/confsched/KaigiAppTest.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableScreenRobot.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridTab.kt
- close #290 
- Add TimetableScreenTest to verify changing event day.
- For this, I added two tests switching event day (list / grid)
- #290 
Before | After
:--: | :--:
NotExist | <img src="https://github.com/user-attachments/assets/e3df4742-c5f2-472b-b251-4008769649a4" width="300" />
NotExist | <img src="https://github.com/user-attachments/assets/8db48993-46df-4885-b281-77401a7e6a94" width="300" />
> Verify changing tab on Timetable screen

- app-ios/Sources/TimetableDetailFeature/TimetableDetailView.swift
- close #307 
- Make `VStack` full-width in SwiftUI View.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix a header background in case of the detail that the title is too short and the speakers are nothing in iOS

- gradle/libs.versions.toml
- close #257
- Changed `org.jetbrains.androidx.navigation:navigation-compose` to version 2.8.0-alpha08 to avoid crashes on screen transitions in release (and debug) builds as a workaround.
- https://github.com/JetBrains/compose-multiplatform/issues/4711
Unrelated to UI
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/ed8ec293-5836-4199-8aa2-3ffd2a0540ad" width="300" > | <video src="https://github.com/user-attachments/assets/e93ddd2d-8f84-473e-9963-ccb9e332c259" width="300" >
> Fix crash when enabling minification

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- feature/eventmap/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreenTest.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
- close #303 
- Remove the BackButton on the EventMap screen as it is not needed.
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI
Before | After
:--: | :--:
Before | After
:--: | :--:
> Remove BackButton in eventmap screen

- core/testing-manifest/src/main/AndroidManifest.xml
- close #302
The launcher app shows one app icon.
> issue-302 Remove intent filter of HiltTestActivity

- feature/eventmap/src/iosMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapViewController.kt
- close #334
- Bug occurred because of undefined param in eventMapViewController, so remove it.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [feature/#334] Remove useless param of EventMapScreen in iOS

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- close #316 
- When come back from sub screen (e.g. Contributor screen on About tab), selected item of bottom nav bar will be refreshed.
- Enable to keep selected it.
- #316 
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/5579e5b0-804a-4760-96b8-31078843f8ec" width="300" > | <video src="https://github.com/user-attachments/assets/5d7ab955-65aa-421e-8d52-8b5380d4ab94" width="300" >
> Prevent refreshing BottomNavBar selected item

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- When using 3-button navigation, the bottom navigation and navigation bar interfered with each other. Margins now scale based on WindowInsets.
Before | After
:--: | :--:
Before | After
:--: | :--:
> Change the bottom margin of bottom navigation based on WindowInsets

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemCard.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemTag.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridHours.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridRooms.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableGrid.kt
- close #333
- Update several components of the `TimetableList` screen to use the correct text styles and appearance
- Update several components of the `TimetableGrid` screen to use the correct text styles and appearance
- Expected design is based on [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54795-26746&t=agwbDcGBmYwrCwd5-0)
> Timetable text appearance alignments

- core/model/src/androidMain/kotlin/io/github/droidkaigi/confsched/model/BlurSupport.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/BlurSupport.kt
- core/model/src/iosMain/kotlin/io/github/droidkaigi/confsched/model/BlurSupport.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- close #345
- Haze is a great library, but it doesn't work on Android 11 or below
- Introduce `isBlurSupported()` to determine if a device can or cannot utilize blur
- Change opacity of scrim to 40% for supported devices, matching Figma
- Decide which color to pass to `HazeStyle` depending on whether blur is supported
- https://chrisbanes.github.io/haze/
API 34 | API 27
:--: | :--:
<video src="https://github.com/user-attachments/assets/cb2d4bae-9813-43bb-89f4-28eb9d5459b6" width="300" > | <video src="https://github.com/user-attachments/assets/520f2aa5-a69f-4a03-82a9-15fdf9e4a650" width="300" >
> Use non-blurred scrim for GlassLikeBottomNavigation on devices without support for blur

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidGradleDsl.kt
- close #301 
Bump targetSdkVersion to 34. 
I checked the list below. But there were no problems, so I didn't do anything.
- Execute `./gradlew app-android:assembleProdRelease`
- Launch activity using an implicit intent
- Google Calendar
- YouTube
- X (Twitter)
- Google Chrome
- OSS Licenses
I checked other where UUIDs and regular expressions, I can't found problems.
- https://developer.android.com/about/versions/14/behavior-changes-14
Before | After
:--: | :--:
Before | After
:--: | :--:
> Bump targetSdkVersion to 34

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenPresenter.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- close #341 
- Replace `Pair<String, String>` with the `TimeSlot` class to make it easier to understand.
- The property `TimeSlot.key` is required to avoid the runtime error related to LazyList.
```kotlin
FATAL EXCEPTION: main
Process: io.github.droidkaigi.confsched2024.dev, PID: 15075
java.lang.IllegalArgumentException: Type of the key TimeSlot(startTimeString=10:30, endTimeString=11:00) is not supported. On Android you can only use types which can be stored inside the Bundle.
at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:79)
at androidx.compose.foundation.lazy.layout.LazySaveableStateHolder.SaveableStateProvider(LazySaveableStateHolder.kt:85)
at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactoryKt.SkippableIte …
```
> Replace Pair with a new data class TimeSlot

- core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardDataStoreModule.kt
- core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardRepositoryModule.kt
- core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched/data/user/DataStoreModule.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/DefaultProfileCardRepository.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardDataStore.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardJson.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ProfileCard.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ProfileCardRepository.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ProfileCardTheme.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/data/TestDataStoreModule.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/ProfileCardScreenRobot.kt
- feature/profilecard/build.gradle.kts
- feature/profilecard/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenTest.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt
- define logic to save profilecard
- ProfileCardJson for saving ProfileCard to DataStore
- https://github.com/DroidKaigi/conference-app-2024/commit/0152574dc77b2a90d4081eaceef7637f9562014e
- ProfileCardDataStore
- https://github.com/DroidKaigi/conference-app-2024/commit/74a2b60063d48ad5f760323b2994df718ee493b6
- ProfileCardRepository
- https://github.com/DroidKaigi/conference-app-2024/commit/415cd749e597e8add59381ddf3ee86fb3be8933f
- integrate UI layer
- https://github.com/DroidKaigi/conference-app-2024/commit/0241600713da6e2ec548d0fc950e639ac0354d37
- add ProfileCardTheme
- https://github.com/DroidKaigi/conference-app-2024/commit/df9860950dde8e126659e2dfbcec84c3777004a9
- add test
- https://github.com/DroidKaigi/conference-app-2024/pull/361/commits/cd6efbbfebb25f9cdd1413f21d8a4a7e2f167a18 …
> save profilecard to datastore

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutContentColumn.kt
- close #227 
- Change the text color of the Credits and Other items in the AboutContentScreen
- The default is primaryFixed, but if you want to specify a different color, you can specify it in the AboutContentColumn argument.
- 
Before | After
:--: | :--:
> feature:add an argument to the AboutContentColumn

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- none
- Since the return value of `Context.getSystemService` is originally nullable, a null check is necessary. To make this issue more noticeable, Kotlin extension is used.
- https://developer.android.com/reference/android/content/Context#getSystemService(java.lang.String)
- https://developer.android.com/reference/kotlin/androidx/core/content/package-summary#(android.content.Context).getSystemService()
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add a null check for the return value of Context.getSystemService

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableScreenRobot.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridHours.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridRooms.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableGrid.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableSheet.kt
- close #340 
- At present, each Timetable is sharing scroll state between conference date.
- it means if you switch conference date, switched timetable displayed as scrolled.
- By separating passed scrollstate or timetablestate, trying to adjust it.
- #340 
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/de688e83-8aa6-45f5-b3ed-fa2eca1ef4c5" width="300" > | <video src="https://github.com/user-attachments/assets/d1685c4f-6939-44e5-b832-ea0ef6b4d620" width="300" >
<video src="https://github.com/user-attachments/assets/1ea66460-89f2-4b69-8308-efcc1ced93f4" width="300" > | <video src="https://github.com/user-attachments/assets/76d16c66-bbfc-43d6-a159-93993e4634fc" width="300" >
> Not to share scroll state between conference date tabs

- feature/eventmap/build.gradle.kts
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/navigation/EventMapDestination.kt
- close #352 
- Apply type safe compose navigation in event map screen
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/c3949ec0-1866-4d90-87c6-2efc13136843" width="300" > | <video src="https://github.com/user-attachments/assets/4cdbfbb8-f190-49e7-bd9f-626f17e0b43f" width="300" >
> [feature/#352] Apply type safe compose navigation in event map screen

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- close #225
- Reverse title and time in timetable grid
- also fixed the spacing with the title
- Side note
- When I look at Figma, there is no space to only the left of the tilde, is this the correct design?
- <img width="303" alt="image" src="https://github.com/user-attachments/assets/7928dce9-494b-44a8-b725-8a54454805ab">
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Reverse title and time in timetable grid

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpIosPlugin.kt
- close #12 
- Use applyDefaultHierarchyTemplate.
- Remove unnecessary definition.
- Following the above, the warning disappears when Gradle sync.
- https://kotlinlang.org/docs/multiplatform-hierarchy.html
Nothing.
Nothing.
> Use applyDefaultHierarchyTemplate

- app-ios/Sources/App/RootReducer.swift
- app-ios/Sources/TimetableFeature/TimetableListView.swift
- app-ios/Sources/TimetableFeature/TimetableReducer.swift
- close #286
- Added in a way to send the selected item to the timetable detail screen
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/41b6fece-c252-498c-bef4-e485f1c08ffc" width="300"  alt="before" title="Before">  |  <video src="https://github.com/user-attachments/assets/c5f5fd2e-38a4-43ba-aa54-6f1d964abdcb" width="300"  alt="after" title="After">
> fixed link between timetable and timetable detail

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableGrid.kt
- close #242
- The background of the TimeTablePreview was transparent, so it was changed to black by using theme and surface
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> add a background by using surface for TimetablePreview

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- close #279 
- TimetableGridItem has a vertical limitation because it can be pinch-in, and I thought it would look better to make the width smaller to match the height.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/69c191f0-99ed-4a99-931e-275a58d2f2bd" width="300" > | <video src="https://github.com/user-attachments/assets/e6f3157c-174b-45ad-8690-6e0e66edddcb" width="300" >
> speaker icons is always circle shape in TimetableGridItem

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt
- close #386
- I fixed the StaffApi url in [StaffApiClient.kt](https://github.com/DroidKaigi/conference-app-2024/blob/a3d0c2a8e928b1c5c35c454086321535ded66a52/core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/staff/StaffApiClient.kt#L17)
- I added comment in the API
Before | After
:--: | :--:
> Fix Staff API url and return actual value

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/DefaultProfileCardRepository.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardDataStore.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/profilecard/ProfileCardJson.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ProfileCard.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ProfileCardRepository.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt
- close #371
1. Converted ProfileCard to a sealed interface to represent the states of loading, no data, and data exists.
2. Modified the Data layer processing to handle the data structure of ProfileCard after the conversion.
3. Enabled the UI to display a loading indicator based on the data structure of ProfileCard after the conversion.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/823bb4b3-4ec9-423b-a0b3-7b0e77d439a3" width="300" >  |<video src="https://github.com/user-attachments/assets/bb4fd43d-7b97-42a9-93a0-5271122cca93" width="300" >
> :recycle: Improve first launch UX when profilecard already saved

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- close #387
- Made it so that the TopAppBar is immediately hidden when scrolling down and immediately appears when scrolling up.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/b4f368a7-7d23-4340-9642-26753e8c629e" width="300" > | <video src="https://github.com/user-attachments/assets/527e13e9-7028-47bc-85eb-f04f1f841b2b" width="300" >
> :wrench: Change scrollBehavior in TimetableItemDetailScreen.

- app-ios/Makefile
- app-ios/README.md
- none
- To make the app-ios build process easier and more reliable, added `make bootstrap`. The previous `make open` command seemed insufficient for the setup.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add make bootstrap for app-ios

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidComposePlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/ComposeGradleDsl.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpComposePlugin.kt
- gradle/libs.versions.toml
- close #406
- Tidy up the composeCompiler plugin declaration in `build-logic`
- Apply `enableStrongSkippingMode` to both the Android Compose & KMP Compose plugins
- Clean up the existing declaration of compose resources with a DSL (similar to other `XxxGradleDsl.kt` files)
- More info on strong skipping mode for Compose: https://developer.android.com/develop/ui/compose/performance/stability/strongskipping
> Refactor compose.resources declaration in build logic & enable Compose strong skipping mode

- app-ios/Sources/TimetableFeature/SampleData.swift
- app-ios/Sources/TimetableFeature/TimetableListView.swift
- app-ios/Sources/TimetableFeature/TimetableReducer.swift
- close #291
- Fixed basic tab functionality for iOS
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fixed tab on timetable. (This design may change soon)

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/EventMapApiClient.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/EventMapEvent.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapItem.kt
- close https://github.com/DroidKaigi/conference-app-2024/issues/403
- Added message property to EventMapEvent class
- Added the mapping for MessageResponse to EventMapEvent#message.
- Added logic to display EventMapEvent#message when it is non-null.
- none
Before or when EentMapEvent#message is null | After
:--: | :--:
> Add message for EventMapEvent

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutDroidKaigiDetailSummaryCard.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutDroidKaigiDetailSummaryCardRow.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutDroidKaigiDetail.kt
- close #397 
- Update the AboutDroidkaigi section design to match the Figma design.
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54985-75928&t=N5b6Q2AZf7PVvvKD-4 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Feature/397 AboutDroidkaigi section design

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/FlipCard.kt
none
It was flipping and flickering as soon as I tapped the card, so I change the setting to flip it over after rotating more than 90 degrees.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/77d02ff6-f925-47ab-b022-8922d73a657a" width="300" > | <video src="https://github.com/user-attachments/assets/44b18eba-84fd-4d33-8972-7474d171f065" width="300" >
> Improve flip animation

- feature/favorites/src/commonMain/composeResources/values-ja/favorites_strings.xml
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/component/FavoriteFilters.kt
- close #456 
- Updated the UI of the Favorite/Empty screen with the following changes:
1.	Adjusted the padding of the buttons at the top of the screen to match the Figma design.
2.	Corrected the line break in the text according to the Figma design.
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55518-43653&t=pGcYDGfI9eDBOFFN-4
Before | After
:--: | :--:
> Align the UI of the Favorite/Empty screen with the Figma design proposal.

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/EventMapApiClient.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/response/EventResponse.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/EventMapEvent.kt
- close #465
- Turn `EventResponse#message` from `MessageResponse` into `MessageResponse?`
- The UI layer already handles this being absent, so no changes needed
- We can now provide a `null` value from the API for this field
- Added some variation to `EventMapEvent` fake data so that we can see the absent message in the app
- -/-
> Make EventResponse#message field nullable

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableItemDetailScreenRobot.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailPresenter.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- nothing
- When we tap the snack bar button that is shown when we tap a favorite button on the session details screen, this app shows the favorites list screen.
- nothing
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/67bfc25a-42d8-4be5-8aa2-1dff417f8faf" width="300" >
> Navigate from session detail to favorite list by snackbar action

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- no issue
- Use 'Enum.entries' available since Kotlin 1.9.
- Lint recommends 'Enum.entries' instead of 'Enum.values()'
- https://youtrack.jetbrains.com/issue/KT-48872
> 🧹 Use Enum.entries

- gradle/libs.versions.toml
- no issue
- Update to the latest patched version of Android Studio.
- Since this is a patched version, there are no additional migration items
- [Android Studio Koala | 2024.1.1 Patch 2 release note](https://androidstudio.googleblog.com/2024/08/android-studio-koala-202411-patch-2-now.html)
> Update AGP 8.5.2

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/NetworkService.kt
- core/model/src/androidMain/kotlin/io/github/droidkaigi/confsched/model/AppError.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/AppError.kt
- core/model/src/iosMain/kotlin/io/github/droidkaigi/confsched/model/AppError.kt
- core/ui/src/commonMain/composeResources/values-ja/strings.xml
- core/ui/src/commonMain/composeResources/values/strings.xml
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/AppErrorMapper.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/ComposeResourceErrorMessage.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/PresenterDefaultsProvider.kt
- close #404
- I have not been assigned to an issue, but I thought that no one but me would show up to do it, so I created this PR.
- Created `knownPlatformExceptionOrNull` and `InternetConnectionException` to match The following [comments](https://github.com/DroidKaigi/conference-app-2024/issues/404#issuecomment-2290206708) 
>How about adding a expect function like this?
>
>expect fun knownPlatformExceptionOrNulll(e: Exception): AppError?
>
>actual fun knownPlatformExceptionOrNulll(e: Exception): AppError? {
>if(e is UnknownHostException) {
>return AppError.InternetConnectionException(e)
>}
>return null
>}
- Composable function `ComposeResourceErrorMessages` to display network connection failure in English or Japanese
- Error wording in Japanese and English is my own wording
Before | …
> to be able show connection failed message

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/RoomTheme.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/TimetableRoomExt.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemTag.kt
- close #211 
- fix design of tag icon.
- fix theme color of flamingo.
- nothing
Before | After
:--: | :--:
> Session detail screen: Room and language layout slightly differs from Figma

- feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
- feature/sessions/src/commonMain/composeResources/values/strings.xml
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- no issue
- Typography use labelSmall instead bodySmall
- Icon use session room instead of schedule
- Similarly contentDescription was fixed
- `-` to `~`
- `~` There appears to be a space in the after, but it is not actually there. Not adjusted this time
- https://github.com/DroidKaigi/conference-app-2024/pull/376#issuecomment-2286502405
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55495-40872&t=5C229MEc5Q7tFuTf-4
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix appearance of time in TimetableGridItem

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- nothing
- The following two PR fixes were causing the build to fail, so we have fixed them.
- https://github.com/DroidKaigi/conference-app-2024/pull/470
- https://github.com/DroidKaigi/conference-app-2024/pull/475
- nothing
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix build error on TimetableGridItem.kt

- feature/about/src/commonMain/composeResources/values-ja/strings.xml
- nothing
- I fixed a typo in the title of the about screen.
- Droidkaigi → Droid「K」aigi
- nothing
Before | After
:--: | :--:
> Typo in the about screen title

- feature/about/src/commonMain/composeResources/values/strings.xml
- nothing
- I fixed a typo in the English version “About screen”
- I fixed the missing items in "#487".
Before | After
:--: | :--:
> Fixed DroidKaigi typo

- app-ios/Sources/TimetableFeature/Resource/Localizable.xcstrings
- app-ios/Sources/TimetableFeature/TimetableListView.swift
- close #447
- Fix timetable title to allow translation into Japanese
- 
English | 日本語
:--: | :--:
Before | After
:--: | :--:
> Translate timetable title into Japanese

- core/model/build.gradle.kts
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/DroidKaigi2024Day.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/Timetable.kt
- core/model/src/commonTest/kotlin/io/github/droidkaigi/confsched/model/DroidKaigi2024DayTest.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableScreenRobot.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/compositionlocal/LocalClock.kt
- feature/sessions/build.gradle.kts
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridTab.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableSheet.kt
- gradle/libs.versions.toml
- close #463 
- Add unit tests for DroidKaigi2024Day:
Introduce `kotlin-test` to allow for multiplatform unit tests of logic that doesn't require any UI components
- Simplify DroidKaigi2024Day enum and fix end-of-day logic:
The current declaration makes the day "end" at 23:59:59, but in the last second the behavior would've been undefined. 
Declare the end time explicitly with 999_999_999 nanoseconds to cover the entirety of each day
- Extend fake clock capabilities & add robot test for the second day, too:
This required a change in how the tabs store their selection state (not sure why it was hardcoded at `selected = false` before...)
- -/-
> Add tests to verify DroidKaigi2024Day and the initially displayed timetable tab

- .github/workflows/ios-build-test.yml
- app-ios/App/App.xctestplan
- app-ios/Makefile
- app-ios/Package.swift
- app-ios/Tests/TimetableTests/TimetableTests.swift
- close #440 
- Added github action to test for iOS
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> iOS test action

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/component/ClickableLinkText.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailContent.kt
- none
- In the DescriptionSection, I thought it would be even better if the More button had an animation instead of just switching quickly.
- `ClickableTextExpandAnimateDurationMillis = 1000` may be a bit long, but I set it because I thought it would be richer UI and not disturb the user.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/91f3b2ce-34a6-4a90-8c90-1065dbfcee6f" width="300" > | <video src="https://github.com/user-attachments/assets/61b69787-a17d-480a-98a4-e75fa9e58926" width="300" >
https://github.com/user-attachments/assets/da33a610-9289-48c5-a3f2-a9b46df8f073
>  In TimetableItemDetailScreen, add animations to DescriptionSection

- app-ios/Sources/AboutFeature/AboutView.swift
- app-ios/Sources/App/RootReducer.swift
- app-ios/Sources/App/RootView.swift
- app-ios/Sources/EventMapFeature/EventMapView.swift
- app-ios/Sources/FavoriteFeature/FavoriteView.swift
- app-ios/Sources/StaffFeature/StaffView.swift
- app-ios/Sources/TimetableFeature/TimetableListView.swift
- close #428
- Replace native tabbar to custom floating tabbar
- Background is clipped by iOS systemMaterial glass.
- I'm not sure how far we could go with the design in iOS, so I addressed the UI first.
- 
Android | Before | After
Before | After
:--: | :--:
https://github.com/user-attachments/assets/167039eb-c0b5-418b-a228-2f621fbb7ea4
> Impl bottom floating material glassed tabbar in iOS

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt
- close #507 
- Move 'if the string is empty, show an error message' logic to ProfileCardScreenPresenter
- Make `ProfileCardError` data class to store error message values.
- When the input value is changed at the text fields, added EditScreenEvents are triggerd.
- In the presenter, caluculate the error message values for the triggered event.
⚠️ Specifiaction Changes
Before the change, there was an error message in the initial state.
I considered this an not good user experience.
So, the changed error logic only works if there is a change in the input.
If the behavior before the change is more correct in this point, please let me know so I can try to correct it again.
- 
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/67e5c6c2-bdfb-47b6-b10b-b259970b28da" …
> Move error logic to presenter about Card Editing

- core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched/data/about/AboutRepositoryModule.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/about/DefaultAboutRepository.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/AboutRepository.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreenPresenter.kt
- close #484 
- Make `AboutUiState`, `AboutScreenPresenter` and `AboutRepository` to get app version from buildConfigProvider
- 
Nothing
Nothing
> Use app version from BuildConfigProvider at AboutScreen

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sponsors/SponsorsApiClient.kt
- close #385
- I fixed the SponsorsApi method in DefaultSponsorsApiClient
- I added comment in the API
Before | After
:--: | :--:
> Use this year's Sponsor API

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/component/ClickableLinkText.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailContent.kt
- close https://github.com/DroidKaigi/conference-app-2024/issues/511
- The more button in the `DescriptionSection` of the `TimetableItemDetailScreen` was displayed even if the session description was short.
- I have changed the specification to display the session description even if it is short.
- `short` means less than 7 lines of description.
- = https://github.com/DroidKaigi/conference-app-2024/blob/a1a0fdc8d53d1bb078644e4a0ae661feecf9b08f/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailContent.kt#L117
-
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/9bddd21d-af1f-4b1b-b046-cc7a602017a7" width="300" /> | <video …
> Show more button only if session description is long

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/PaddingValuesExt.kt
- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreen.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/SearchList.kt
- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreen.kt
- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/section/SponsorsList.kt
- feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt
- close #471
- On some screens, contents aren't displayed under the bottom nav bar (please refer "before" images) 
- I'd like to adjust bottom nav bar area like as timeline screen
- 
Before | After
:--: | :--:
> Enable to show contents under the bottom nav bar

- app-ios/Sources/EventMapFeature/EventItem.swift
- close #427
- Show message when `EventMapEvent#message` is non-null
- https://github.com/DroidKaigi/conference-app-2024/pull/424
(I referred to the Android side implementation)
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add message to EventMap

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- None.
- Addressed an issue where a timetable item would keep animating when scrolling is started after tapping on the timetable item.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/4728489d-52ae-4b4f-b7a2-4586af002411" width="300" > | <video src="https://github.com/user-attachments/assets/efa46313-b616-49ab-811e-2284a57a7e8e" width="300" >
> :wrench: Fix the TimetableScreen so that it does not animate when it is scrolling.

- app-ios/Sources/SponsorFeature/SponsorView.swift
- close #429
- Use LazyVGrid in each sponsors section.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Refine sponsor grid view

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/rules/RobotTestRule.kt
- None.
- Every time I implemented VRT, I wrote the following temporary code in the xxxTest file to check the contents of the semantics tree.
```kotlin
@Before
fun setUp() {
ShadowLog.stream = System.out
}
```
```kotlin
composeTestRule
.onRoot()
.printToLog("TESTTEST")
```
- It was necessary to add this description when implementing the test because without it, the log would not be displayed anywhere even if printToLog is written.
- Adding the isShowLogOnConsole option facilitates log display and improves development productivity.
> :recycle: Added a log output option that is useful when implementing VRT.

- app-ios/Sources/FavoriteFeature/FavoriteView.swift
- app-ios/Sources/SearchFeature/SearchView.swift
- nothing
- Due to [SE-0364](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md), protocol compliance of external modules will be subject to warnings unless the `@retroactive` attribute is declared.
- Xcode 16 shows SE-0364 warning even on Swift 5.10. Use the `hasFeature()` macro for conditional compilation.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add (at)retroactive to the extension to address the Xcode 16 warning.

- app-ios/Sources/Model/Selectable.swift
- app-ios/Sources/SearchFeature/SearchView.swift
- close #443
- Remove workshop day from search filter options
- Add `options` to `Selectable` protocol
- Default value is `allCases`
- Override `options` in `DroidKaigi2024Day`
- It is possible to overwrite `allCases` , but I thought `allCases` should list all cases, so I created Options.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Search Feature: Remove filter of Workshop Day

- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapTab.kt
none
- I implemented it because it would be nice to be able to drag instead of tapping a button to switch between maps.
- Crossfade looks better with Animation than with a quick changeover.
- `ChangeTabDeltaThreshold = 20f` is a value that I found to be just right in terms of my own operational feel.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/24e718d7-f1ef-426f-9b7f-7fdbce500266" width="300" > | <video src="https://github.com/user-attachments/assets/96dca727-554a-45db-959a-cd5691df44c6" width="300" >
[Android developers - drag-swipe-fling](https://developer.android.com/develop/ui/compose/touch-input/pointer-input/drag-swipe-fling)
At first I used `pointerInput` to get the amount of drag, but now I use `draggable` because I could not scroll with my …
> Added drag gesture and crossfade in EventMapTab

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #593 
- Rearranged the order of modifiers in EditScreen so that nestedScroll works correctly.
- 
Before | After
:--: | :--:
> fix: AnimatedTextTopAppBar does not function in ProfileCardScreen

- core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/EventMapApiModule.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/EventMapApiClient.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/response/EventMapResponse.kt
- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/eventmap/response/ProjectResponse.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/data/eventmap/FakeEventMapApiModule.kt
- close #602
- Change EventMap API endpoint to actual one (mentioned in the Issue)
- Use the data fetched from the API as default
- Rename `event` to `project`
- I wonder if it would be better that we do rename on module level
Before | After
:--: | :--:
> Fix EventMap API endpoint and use actual data from the API

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemCard.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- close #608
- Use FlowRow when show `TimetableItemTag`
- Replace `Spacer` with `FlowRow#horizontalArrangement` and `FlowRow#verticalArrangement`
- 
Screen | Before | After
:--: | :--: | :--: 
Timetable tab | <img src="https://github.com/user-attachments/assets/79be25ad-f7bb-4dea-9ef6-e4198258e6d9" width="300" /> | <img src="https://github.com/user-attachments/assets/950c1b33-890f-4945-8dd9-6b1d809c5426" width="300" />
Favorite tab | <img src="https://github.com/user-attachments/assets/6fa76ff5-bbda-4e40-86e3-d5beab775bde" width="300" /> | <img src="https://github.com/user-attachments/assets/245c1eae-ce6f-4246-83d7-14ec18d7d8b1" width="300" />
Before | After
:--: | :--:
> Use FlowRow when show TimetableItemTag

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/animation/FavoriteAnimation.kt
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/animation/FavoriteAnimationScope.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeNavRail.kt
- close #611 
- Add animation of favorite on timetable list when GlassLikeNavRail is displayed.
- ※Remain GlassLikeBottomNavigation's current animation.
- 
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/9ac46aa6-1db0-4e25-a49e-009484c1af87" width="300" > | <video src="https://github.com/user-attachments/assets/b3c7f32a-9359-4541-bda4-0517c5156252" width="300" >
<video src="https://github.com/user-attachments/assets/e18009bd-aa20-4b9c-a278-fa9f2adef38a" width="300" > | <video src="https://github.com/user-attachments/assets/2980a7fd-c9a8-415e-b0ba-bda261d869f6" width="300" >
> Favorite animation for ClassLikeNavRail

- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/section/SponsorsList.kt
- close #614
- Add padding at the bottom of Sponsors Screen
- Change start and end padding to match design
none
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add padding at the bottom of Sponsors Screen

- app-ios/Sources/SponsorFeature/SponsorView.swift
- https://github.com/DroidKaigi/conference-app-2024/pull/610
- This is the same fix for iOS App
- 
After1 | After2
:--: | :--:
Before | After
:--: | :--:
> Change the background color of the sponsor logo in iOS

- app-ios/Sources/Theme/ColorAsset+Sendable.swift
- app-ios/Sources/Theme/FontConvertible+Sendable.swift
- Added an extension to make SwiftGen-generated types conform to unchecked Sendable
- Why didn't this PR customize the stencil?
- Because it had `lazy var color: Color` and it seemed like I had to make stencil `@unchecked Sendable `after all.
-  Additionally, since the class involved are Color or Font, the likelihood of data races in normal usage scenarios is minimal.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add extension for SwiftGen code to conform to unchecked Sendable

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/SearchScreenRobot.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenTest.kt
- None.
1. todoChecks were left unchecked, so a correction has been made to check them.
2. the part where the value is passed from ScreenTest side was moved to Robot and the process was hidden from Test side.
> :recycle: Make additional corrections to SearchScreenTest because it is not fully implemented.

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/ContributorsScreenRobot.kt
- feature/contributors/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreenTest.kt
> :wrench: Move the ContributorsScreenTest implementation to ContributorsScreenRobot and hide it.

- app-ios/Sources/KMPClient/Helpers/Container.swift
- Container type conforms to `Sendable`
- https://twitter.com/omochimetaru/status/1825402485084979428
Before | After
:--: | :--:
Before | After
:--: | :--:
> Container conform to `Sendable` to resolve Swfit 6 warning

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutDroidKaigiDetail.kt
- close #612 
- The issue occurred when the description text fit within a single line relative to the device's width.
- The layout was adjusted to always use the full screen width, ensuring the description text is consistently centered, even on a single line.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> fix: center single-line description on AboutScreen

- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt
- close #564 
- As title, add tests about date switching and grid timetable combination
> Add test on TimetableScreenTest about date tab and grid combination

- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/component/SponsorItem.kt
- close #628 
- As commented [here](https://github.com/DroidKaigi/conference-app-2024/issues/628#issuecomment-2297227838), there was also a problem in 2023's app.
- And I tried to solve `LazyVerticalGrid + coil's painter problem` with `maxBitmapSize` (added to coil pj recently) but it was not a silver bullet.
- Finally, I counldn't find the cause of this issue :pray: So I would like to use AsyncImage as workaround about it.
- If it is not desired, please close this pr :bow: 
- https://github.com/DroidKaigi/conference-app-2024/issues/628#issuecomment-2297227838
- https://github.com/DroidKaigi/conference-app-2023/issues/1088
- https://github.com/coil-kt/coil/issues/1610
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/fd34c0b8-edb8-4dea-90aa-f2b7a83a0102" …
> use AsyncImage for SponsorItem

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
I noticed that there is incorrect query for intent and it always results to false. This function can be confirmed against such like play store URLs.
- https://github.com/DroidKaigi/conference-app-2024/blob/c79cdf50d29ecd0837b2ed8414e2df54f1d14eff/app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt#L379-L380
- https://github.com/DroidKaigi/conference-app-2024/blob/c79cdf50d29ecd0837b2ed8414e2df54f1d14eff/app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt#L387-L388
- https://github.com/DroidKaigi/conference-app-2024/blob/c79cdf50d29ecd0837b2ed8414e2df54f1d14eff/app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt#L392-L393
> Fix incorrect intent list

- app-ios/Sources/TimetableFeature/TimetableListView.swift
- close #618 
- Added 16 end paddings to gridView.
- The bottom padding was specified as 16. However I have changed it to 60(including the height of the bottom tab), to match the case of the List View. Therefore, we have added 68(60 +  default spacing 8).
- 
Before | After
:--: | :--:
> added margin to timetable grid view #618

- app-ios/App/App.xcodeproj/project.pbxproj
- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/PresenterDefaultsProvider.kt
- close #527
- Add the KMP resource
- https://youtrack.jetbrains.com/issue/KT-66790
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix iOS KMP resources

- app-ios/Sources/ContributorFeature/ContributorView.swift
- app-ios/Sources/KMPClient/Views/KmpContributorComposeViewControllerWrapper.swift
- close #438 
- Added logic to open sheet when tapping contributor button in ContributorView
- 
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/511822e4-23bc-453b-9640-5b855e2a4bf8" width="300" >
> Added logic to open sheet when tapping contributor button in ContributorView

- app-ios/Sources/ContributorFeature/ContributorView.swift
- app-ios/Sources/ContributorFeature/KmpPresenterContributorView.swift
- app-ios/Sources/ContributorFeature/Resources/Localizable.xcstrings
- app-ios/Sources/KMPClient/Views/KmpContributorComposeViewControllerWrapper.swift
- close #436 
Modified header tab on ContributorView because slider text is missing
- 
Before | After
:--: | :--:
> [iOS] Modify header tab on ContributorView

- app-ios/Sources/SearchFeature/Resources/Localizable.xcstrings
- app-ios/Sources/SearchFeature/SearchView.swift
- https://github.com/DroidKaigi/conference-app-2024/issues/442
- We have created a new `private func searchCategoryFilterChip` so that you can filter by category list.
- All Category can get from timetable TimetableCategories get timetable model.
- (TimetableCategory don't have to conform to Selectable protocol.)
- In addition, we are adjusting the localization strings required for SearchView.
ja | en
:--: | :--:
<video src="https://github.com/user-attachments/assets/ddac6e7c-fa0f-4fa4-a314-82f78c74af61" width="300" > | <video src="https://github.com/user-attachments/assets/0fdb5c65-f529-408b-a525-e348bafd93d7" width="300" >
> Enable to display category chip data (from State) in SearchView 

- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/Filters.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/Timetable.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/SearchScreenRobot.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenPresenter.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenPresenter.kt
- close #496 
- nobonobopurin-san says at issue, I'd like to adjust search screen such as followings
- all filters are not set and search text is empty -> nothing to show
- some filters are set or search text is not empty -> show search result
- filter criteria are not empty and filter result is empty -> show empty message
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54953-72675&t=Lg4yETysBVrI2dXJ-0
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/ac8a2a35-c0d4-44d8-889d-4fa3c7063d98" width="300" > | <video src="https://github.com/user-attachments/assets/e106c343-7da5-465e-839c-6b5cf0f45e96" width="300" >
> Not to show any card at first on SearchScreen

- core/data/src/iosMain/kotlin/io/github/droidkaigi/confsched/data/DataModule.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/EventMapRepository.kt
Currently, iOS app get fake event map data. Since api to get real event map data was implemented on server, I replaced EventMapApiClient dependency.
- 
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/12022084-596f-4f6e-bdbd-3e5e3fbf82e5" width="300" >
> [iOS] Changed to get real event map data

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/SettingsScreenRobot.kt
- feature/settings/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/settings/SettingsScreenTest.kt
- feature/settings/src/commonMain/kotlin/io/github/droidkaigi/confsched/settings/component/SettingsItemRow.kt
- feature/settings/src/commonMain/kotlin/io/github/droidkaigi/confsched/settings/section/SettingsAccessibility.kt
- None.
- Adding VRT when implementing SettingsScreen would make the PR too large.
- Therefore, we have added support for the addition of VRT in this PR.
- https://github.com/DroidKaigi/conference-app-2024/pull/637#discussion_r1721171731
> :sparkles: Implemented a test of SettingsScreen.

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailPresenter.kt
- close #655
- Fix to keep the translation state when come back from favorites screen.
- none
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/b4e74ef2-2477-4805-9f48-7e08757bd4be" width="300" > | <video src="https://github.com/user-attachments/assets/53d9efe6-84f7-470f-9109-f5abad262f0f" width="300" >
> Fix to keep the translation state when come back from favorites screen.

- app-ios/Sources/TimetableFeature/Resource/Localizable.xcstrings
- app-ios/Sources/TimetableFeature/TimetableListView.swift
- app-ios/Sources/TimetableFeature/TimetableReducer.swift
- close #617
- Toast message removed from timetable list view. The toast conflicted with the floating tab bar and was not specified in Figma (unlike the detail view) so it was removed to match spec.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Removed problematic toast (was not specified in Figma for this view)

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableTime.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenPresenter.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteList.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteSheet.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- close #378 
- I have added session time in FavoritesScreen
- Figma: https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55499-43411&t=0iY0wsW8N4Frvy7m-4
Before | After
:--: | :--:
Before | After
:--: | :--:
> feat: add session time in FavoritesScreen

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #703 
- Made the profile card scrollable on small devices (when the height is low).
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/e93852c8-dada-42a9-af3f-0e79fbcfe076" width="300" > | <video src="https://github.com/user-attachments/assets/b415c3c5-1ebd-4116-8ce0-cd0fc014c49b" width="300" >
> Profile card scrollable on small devices 

- core/data/build.gradle.kts
- close N/A
- This PR removes a redundant source set dependency from the build script and resolves the following build warning:
```
> Configure project :core:data
w: Redundant dependsOn edges between Kotlin Source Sets found.
Please remove the following dependsOn invocations from your build scripts:
* iosMain.dependsOn(commonMain)
They are already added from Kotlin Target Hierarchy template https://kotl.in/hierarchy-template
```
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Remove redundant source set dependency

- app-ios/Sources/AboutFeature/AboutReducer.swift
- app-ios/Sources/AboutFeature/AboutView.swift
- app-ios/Sources/AboutFeature/Localizable.xcstrings
- app-ios/Sources/App/RootReducer.swift
- app-ios/Sources/App/RootView.swift
- close #604 
I added logic to switch Compose Multiplatform.
For now, Timetable and TimetaleDetail screen of Compose Multiplatform only work. If you transition to other screen, app is crashed.
- 
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/c72cc3a9-efb9-46aa-ad8d-d9f540c43cdb" width="300" >
> Switch Compose Multiplatform

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- close #574 
- Make the tint of the unselected icons in the lower bar equivalent to the design of Figma.
- Unnecessary alpha values were set and removed.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix unselected icons color on bottom bar

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/AnimatedLargeTopAppBar.kt
- N/A
(similar #595)
- On the staff screen and contributor screen, the background color of the top app bar differs from the Figma design when scrolling
- I specified the container color during scrolling, just like in the AnimatedTextTopAppBar.
- [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54953-64722)
Before | After
:--: | :--:
> Fix scroll container color of the AnimatedLargeTopAppBar

- core/designsystem/src/iosMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Type.ios.kt
- gradle/libs.versions.toml
- close #661 
- Updated navigation-compose from 2.8.0-alpha08 to 2.8.0-alpha09.
- The new version, 2.8.0-alpha09, is based on Jetpack Navigation 2.8.0-beta05, which includes important fixes introduced in 2.8.0-beta04.
- https://developer.android.com/jetpack/androidx/releases/navigation#2.8.0-beta04
- > Fixed an issue in Navigation Compose where after canceling the Predictive Back Gesture, the NavBackStackEntry that the user returns to never returns back to the RESUMED Lifecycle State. This also ensures the returning destination correctly animates back in instead of snapping into place after a fling. ([I97a0c](https://android-review.googlesource.com/#/q/I97a0c5fe7fe661a2fadfbb01346676482d426028), [b/346608857](https://issuetracker.google.com/issues/346608857))
- (This is likely the …
> Prevent screen termination on back press during detail transition

- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/component/FavoriteFilters.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteSheet.kt
- close #486 
- Set the padding of FavoriteFilterChip according to the specifications in Figma.
- Synchronized the background color of FavoriteFilters with the TopAppBar based on the scroll state.
- [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55499-43411&t=QBru0VRTzUukjmIe-4)
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/bfbc5ee4-0cea-4785-85b3-93151a302f97" width="300" >|<video src="https://github.com/user-attachments/assets/c0793e0e-c927-44fb-8e48-72f17b17b238" width="300" >
> Fix/486 favorite filters display mismatch 

- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- close #699 
- When scroll timetable and favorites, session hour will be hidden.
- By this pr, show session hour sticky on the display.
- 
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/a02fb9bc-02c0-4ca9-b781-f2faa1897cde" width="300" > | <video src="https://github.com/user-attachments/assets/47184992-d35b-4225-b9e5-9f853f371513" width="300" >
> Stick session hour on Timetable and Farovite List

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridTab.kt
- no issue
- As attached screenshots, conference day tab is not shown correctly if font size is changed.
- Font was not set
- layout was little bit far from figma's
- **If this pr is not fit to the app, please close** :bow:
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54849-12900&t=Kr9KWAn23JSTK8Y7-0
Before | After
:--: | :--:
> Enable to view conference day tab even if font size is large

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KoverEntryPointPlugin.kt
- close #485
- The timing of the application of the KoverPlugin is now done before the project evaluation is complete.
- Without this support, the plugin will be applied while the project has already been evaluated, which will cause an error.
- Thanks to @Aniokrait for providing specific ways to respond! 👏 
- https://github.com/DroidKaigi/conference-app-2024/issues/485#issuecomment-2304251937
> :wrench: Addressed an issue where Kover fails to execute.

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
- close #701 
- The destination of backStackEntry is saved by rememberSaveable. If it goes outside the mainScreen, such as the contribute screen, the destination is saved and can be restored when it comes back. Pass navBackStackEntryRoute to inputs of rememberSaveable and update the value when route changes.
- https://developer.android.com/develop/ui/compose/state#store-state
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/73732ef3-2227-4d5d-938a-c723dfb5a991" width="300" > | <video src="https://github.com/user-attachments/assets/5be9376e-9073-4036-835a-87af0e0ede2b" width="300" >
> fix bottom navigation

- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/share/ShareTextWithImage.kt
- app-ios-shared/src/iosMain/kotlin/io/github/droidkaigi/confsched/shared/share/ImageBitmapToUiImage.kt
- app-ios-shared/src/iosMain/kotlin/io/github/droidkaigi/confsched/shared/share/ShareTextWithImage.ios.kt
- close #731
- Profile cards can be shared in the same way as in Android.
- Currently, ProfileCard has the following two problems, which make it difficult to confirm that it works
1. The keyboard does not close when editing the ProfileCardScreen, so it is not possible to press the Create Card button.
- In the attached video, we have added a note to the implementation to close the keyboard when you tap in the screen.
- Its content is not included as it is not relevant to this PR.
2. The application crashes when ProfileCardScreen is opened with a ProfileCard already created.
- https://github.com/DroidKaigi/conference-app-2024/issues/745
- https://medium.com/mobile-innovation-network/imagebitmap-to-uiimage-compose-multiplatform-0e1f121d7da8
- …
> :sparkles: Implement share ProfileCard from an iOS Compose Multiplatform app

- app-ios/Sources/SearchFeature/SearchView.swift
close #525 
- Use `.searchable`'s `isPresented` parameter to automatically focus the search bar.
- 
When transitioning to search screen
As Is | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Automatically focus search bar when navigating to search screen

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridTab.kt
- close #704
- Adjusted the selected indicator width
- Removed the divider under TabRow
- Other padding adjustments
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55496-41054&t=i5tCQutiAXEMUvIh-4
Before | After
:--: | :--:
> Improved timetable tab design

- core/ui/src/commonMain/kotlin/io/github/droidkaigi/confsched/ui/component/TimetableItemCard.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailBottomAppBar.kt
- close #756
- Similar to [last year's app](https://github.com/DroidKaigi/conference-app-2023/pull/1126/files), invoke some haptic feedback when the favorite button is clicked on a session
- The vibration only happens when you "favorite" a session, not when you "unfavorite" a session
> Perform haptic feedback when favoriting a session (either from the list or detail screens)

- feature/profilecard/src/commonMain/composeResources/values-ja/strings.xml
- feature/profilecard/src/commonMain/composeResources/values/strings.xml
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #729
- close #747
- Using composeResources, add a Japanese version for the button labels
- Using composeResources, update the English share text & add a Japanese version
Before | After (ja) | After (en)
After (ja) | After (en)
:--: | :--:
<video src="https://github.com/user-attachments/assets/b660cfba-4053-4688-b2a3-cddbad6203d5" width="300" > | <video src="https://github.com/user-attachments/assets/dd1d60aa-af13-42f5-bf5e-825238e61f46" width="300" >
> Update button labels & share text for Profile Card

- app-ios-shared/build.gradle.kts
- app-ios/App/App.xcodeproj/project.pbxproj
- None.
- When installing a debug build on an actual iPhone device, the current situation is laborious, so we have made some modifications.
> :wrench: Make modifications so that the build can be done on the actual iPhone device.

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sessions/FakeSessionsApiClient.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/FavoritesScreenRobot.kt
- feature/favorites/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenTest.kt
- close #746
- Added scrolling action method in the favorites screen robot.
- Added a fake with lots of items to scroll through.
- Separated the test setup into an environment with a single item and many items to scroll.
> Add scrolled screen test for FavoritesScreenTest

- app-ios/Sources/CommonComponents/SelectionChips.swift
- app-ios/Sources/FavoriteFeature/FavoriteView.swift
- close #441
- Remove workshop day from favorite view tabs.
- Add `options` argument to `SelectonChips`.
- Default value is `allCases`.
- Override options in `DroidKaigi2024Day`.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Favorite Feature: Remove Workshop Day tab

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
none
- I fixed the ClearButton in EditScreen because it looked different from Figma.
- In Figma, the shadows were blurred, but since it had little effect on the appearance and it seemed impossible to achieve this without a certain amount of ingenuity, a fill was used.
Before | After | Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55588-34615&t=VpbDVe3CvbfpqvxU-4
> In EditScreen, make ClearButton look the same as Figma

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemCard.kt
- close #780 
- Changed so that ripple is displayed according to the color of the room when the TimetableItemCard in the TimetableList is tapped.
- [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54901-56626&t=94gBozQ71SBBtf4Y-4)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/ea82a012-5267-4c5f-8d2b-83c52cd6ed5e" width="300" > | <video src="https://github.com/user-attachments/assets/822d5c62-0bc2-4a3e-8138-94291639fa72" width="300" >
> change rippleColor in TimetableItemCard

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt
- close #766
- The snack bar is no longer needed to be displayed during Edit/Create/SelectImage events, so the processing has been removed.
- The process that changes the value of isLoading has also been removed for the parts that no longer contain a suspend process.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/aedc45f5-1473-4811-8f3a-05593f3dae65" width="300" > | <video src="https://github.com/user-attachments/assets/d8c835b8-767f-4896-9e38-e8ddfed815ab" width="300" >
> :wastebasket: [ProfileCardScreen] The process of displaying the snack bar was removed from areas where it was not necessary.

- app-ios/Sources/TimetableFeature/TimetableListView.swift
- close N/A
- This PR adds text style to the labels on the timetable
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54849-10371&t=fn3hGR5zfnLtiF5A-0
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Add text style to labels on timetable

- app-ios/App/App.xcodeproj/project.pbxproj
- close N/A
- This PR disables "Based on dependency analysis" in the 'Run Script' build phase to resolve the following Xcode warning:
```
Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
```
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Update build phase settings

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailTopAppBar.kt
none
I thought it would be better if I could hide the statusBar when scrolling with TimetableItemDetailTopScreen, so I achieved this by using `consumeWindowInsets` etc. to make the display of the height of the statusbar variable
- [Android developers - Inset consumption](https://developer.android.com/develop/ui/compose/layouts/insets#inset-consumption)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/36bf2116-e907-44d7-97f6-b6d4d436bedd" width="300" > | <video src="https://github.com/user-attachments/assets/c3cff19a-6be8-44b6-87b5-529b3017a747" width="300" >
> In TimetableItemDetailScreen, variable height of statusBar when scrolling

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- close #599 
- Fixed paddings in timetable screen from 16dp to 32dp.
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54876-39860&t=HSvuYQHvkIqBfsAc-4
Before | After
:--: | :--:
Before | After
:--: | :--:
> Chore/599: apply correct padding to timetable screen

- feature/profilecard/src/androidMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/InvertSystemBarAppearance.android.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/InvertSystemBarAppearance.kt
- feature/profilecard/src/iosMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/InvertSystemBarAppearance.ios.kt
- close #762 
- Introduce a side effect, `InvertSystemBarAppearance`, which changes the appearance of the system bars
- Apply this side effect to the `CardScreen` composable, which is the only screen with a light background
> [!WARNING]  
> ~Because of #768, I'm unable to verify the iOS implementation of this. It's based on the following code snippet that I am using in another SwiftUI project of mine to toggle between light and dark theme. I do not know if any other colors change unexpectedly because of this. I may need help from somebody who can compile iOS successfully before we can merge this. 🙇‍♂️~
```swift
let state = true // or false
(UIApplication.shared.connectedScenes.first as? UIWindowScene)?.windows.first!.overrideUserInterfaceStyle = state ? .dark : .light
```
Before | After …
> Invert the system bar appearance on the ProfileCardScreen, matching its light background

- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapItem.kt
- close https://github.com/DroidKaigi/conference-app-2024/issues/784
- The font color of the content title and button text in the EventMapItem has been changed.
- Changed from `LocalRoomTheme.current.primaryColor` to `MaterialTheme.colorScheme.primaryFixed`.
- [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55725-8925&t=mFxMogCMCYJ1nVM0-0)
Before | After | Figma
> changed font color for EventMapItem content title and button text

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/DropdownFilterChip.kt
- close #578
- Dropdown menu background color looked different from the expected color in Figma.
At the time the issue was created, there was also a dropdown menu in the TimetableItemDetailScreen. However, it seems that the dropdown menu is no longer present on that screen. So, I fixex the one in the SearchScreen.
- [Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54965-73535&t=wOtXEZH07pFix45M-4)
**SearchScreen**
Before | After
:--: | :--:
Before | After
:--: | :--:
> 【Fix】fix dropdown background #578

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- close #804 
- Update the touch targets for the header icons on TimetableScreen to 48x48dp, as specified in the Figma design
- Update the ripple effect for the icons to be circular in shape
- [DroidKaigi 2024 App UI – Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54849-12900&t=B5y8N0yYgNnqssOR-0)
Before | After
:--: | :--:
<video src="https://private-user-images.githubusercontent.com/60963155/361245449-c5269137-daa5-493d-9e88-bc40d4d5ef10.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MDY0MzcsIm5iZiI6MTcyNDcwNjEzNywicGF0aCI6Ii82MDk2MzE1NS8zNjEyNDU0NDktYzUyNjkxMzctZGFhNS00OTNkLTllODgtYmM0MGQ0ZDVlZjEwLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI …
> Update the touch targets for the header icons on TimetableScreen

- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapTab.kt
none
- I thought the LanguageSwitcher animation for TimetableItemDetailScreen was great, so I thought we should have a similar animation for EventMapTab.
- This is not directly related to this PR, but I changed it because I thought `isSelected` was better than `selected` as it was easier to see that it was Boolean.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/a5cd3f24-bbfa-4670-b535-cdef619b5fa9" width="300" > | <video src="https://github.com/user-attachments/assets/85cefd75-97aa-4501-8dd2-6cb74e08451c" width="300" >
LanguageSwitcher
https://github.com/user-attachments/assets/7a9db6c3-5125-499a-8833-66203384ba45
> In EventMap, add animtion in EventMapChip icon

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt
- None.
- A back button is now displayed on the top bar of the favorites list when transitioning from the session details screen to the favorites list for both Android and iOS.
- Without the above implementation, you will not be able to go back when you transition from session details to the favorites list on iOS and will not be able to do anything unless you restart the app.
Before iOS | After iOS
:--: | :--:
<video src="https://github.com/user-attachments/assets/8fd39915-41a8-46f8-b9bf-5388eb4cbda7" width="300" > | <video src="https://github.com/user-attachments/assets/9d8c48af-7b24-4d81-8afa-d0ca29e52662" width="300" >
Before Android | After Android
:--: | :--:
<video src="https://github.com/user-attachments/assets/3a990843-acf9-4320-8f29-ea19c5743610" width="300" > | <video …
> :sparkles: [Compose Multiplatform] Added the ability to move from session details to the list of favorites.

- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- core/data/src/iosMain/kotlin/io/github/droidkaigi/confsched/data/DataModule.kt
- None.
- The Repository and DataStore definitions needed for SettingsScreen were missing from the DataModule.
- As it was, SettingsScreen could not be opened from Compose Multiplatform. 
- As I mentioned in my comment, there is probably an unnecessary duplicate description in the DataModule.
- The font does not change now even if I change the settings on the settings screen.
- This will need to be addressed in another task.
<video src="https://github.com/user-attachments/assets/17bcfd48-f4ee-40ac-b92b-09bb731ec52a" width="300" >
> :sparkles: [Compose Multiplatform] The settings screen can now be opened.

- app-ios-shared/build.gradle.kts
- app-ios/Sources/App/RootView.swift
- app-ios/Sources/KMPClient/Views/KmpProfileCardComposeViewControllerWrapper.swift
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt
- feature/profilecard/src/iosMain/kotlin/io/github/droidkaigi/confsched/profilecard/ImageBitmapToUiImage.kt
- feature/profilecard/src/iosMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardViewController.kt
- close #814
- The parts of the UI that were implemented in SwiftUI have been changed to show the UI created in Jetpack Compose.
- Sharing functionality should be outside the scope of this task, so we have not implemented it.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/d83db853-8d8a-4842-bcb9-cdf3b4a2f182" width="300" > | <img src="https://github.com/user-attachments/assets/dbad70eb-e453-445e-be4a-e8f5041a908b" width="300" >
> :recycle: Connecting Compose ProfileCardScreen as an iOS app screen

- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- app-ios/Package.swift
- app-ios/Sources/KMPClient/Views/KmpAppComposeViewControllerWrapper.swift
- None.
- https://github.com/DroidKaigi/conference-app-2024/issues/813#issuecomment-2309812273
<video src="https://github.com/user-attachments/assets/30b01847-26c9-4df0-8768-c89f72e634b7" width="300" >
> :sparkles: [Compose Multiplatform] License screen can now be opened.

- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/component/FavoriteFilters.kt
none
- Same change as #819
- It has the same look as the EventMapChip, so we made it animate the same way.
- Changed to make it easier to understand that it is a Boolean value that changes Visible
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/b5153666-88a3-4007-865c-a77bca40d111" width="300" > | <video src="https://github.com/user-attachments/assets/f82d2e18-f87b-4cb1-9327-1c24e874a31f" width="300" >
https://github.com/user-attachments/assets/5d89787d-02ee-4887-8611-874ed131fc46
> In FavoriteScreen, add animtion in FavoriteFilterChip icon

- core/data/src/iosMain/kotlin/io/github/droidkaigi/confsched/data/DataModule.kt
- None.
- In DataModule, there was a duplicate definition that was removed.
- https://github.com/DroidKaigi/conference-app-2024/pull/823#discussion_r1732847192
> :wastebasket: Removed unnecessary duplicate definitions.

- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenPresenter.kt
none
- In the favorites screen, the filter was returning to its initial value when the device screen size was changed or rotated, so `rememberRetained` was used to prevent this from happening.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/de94b83c-b529-4d5b-8560-5eddf0539af6" width="300" > | <video src="https://github.com/user-attachments/assets/5d4f79e2-015c-4130-ba1b-fb09aca840a5" width="300" >
> In FavoriteScreen, fixed favorite filters being removed when resizing screen

- app-ios/Sources/EventMapFeature/EventItem.swift
- app-ios/Sources/EventMapFeature/EventMapReducer.swift
- app-ios/Sources/EventMapFeature/EventMapView.swift
- app-ios/Tests/EventMapFeatureTests/EventMapTests.swift
- Fix behavior when tapping more detail button on EventMapView
- https://droidkaigi.slack.com/archives/C06LTBTL83U/p1724719868793069
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/aa54ae24-ac98-4169-92ee-eaae47088698" width="300" > | <video src="https://github.com/user-attachments/assets/a8ac27ef-3dcd-45a2-8af9-9de24eaaf1e8" width="300" >
> Fix behavior when tapping more detail button on EventMapView

- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- core/designsystem/src/iosMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/Type.ios.kt
- None.
- A problem with custom fonts not being applied in Compose Multiplatform has been addressed.
- Also, fonts changed in the settings screen are now applied.
- The log obtained by the following code included the name of a custom font in the font family.
- However, the custom font was not applied because the name specified was the font name, not the font family.
```kotlin
for (i in 0 until fontMgr.familiesCount) {
val familyName = fontMgr.getFamilyName(i)
println("Debug: Font family [$i]: $familyName")
}
```
```
Debug: Attempting to load font from path: src/commonMain/composeResources/font/dot_gothic16_regular.ttf
Debug: Font family [0]: Academy Engraved LET
omission (of middle part of a text).
Debug: Font family [29]: DotGothic16
```
Before | After
:--: | :--:
<video …
> :sparkles: [Compose Multiplatform] Fixed so that fonts are applied according to the settings.

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #771
- Adjusted the padding between the `image` label and `add image` button.
- Adjusted the outside padding of the create card button.
- Adjusted the inside padding of the create card button.
[Figma](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55588-8264&t=5GQGixyoAVmum0oZ-0)
Before | After
:--: | :--:
> Fix profile card screen padding

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCardFront.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/PhotoPickButton.kt
- close #840
- Apply a `ContentScale.Crop` to the profile image of both the card and edit versions of the `ProfileCardScreen`
- Remove the "is image square?" check inside `PhotoPickButton`, as well as the dialog when it wasn't
- https://thoughtbot.com/blog/android-imageview-scaletype-a-visual-guide
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/f460cc66-ffa7-47de-8dd3-cc5573b193e3" width="300" > | <video src="https://github.com/user-attachments/assets/b46a7840-b2cf-4b8b-829f-e42916d57b5b" width="300" >
> Allow non-square images to be used for profile by center-cropping them

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/ShareableCard.kt
- close #850
- The shared profile card size was not fixed; it depends on the device screen width. This PR fixes the size of the shared profile card.
Before | After
:--: | :--:
> Fix the size of the shared profile card

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridTab.kt
- close #856
- Prevented negative numbers from being included in the Horizontal padding.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/ad6e697c-e96c-4f47-9ee1-b41d1521398b" width="300" > | <img src="https://github.com/user-attachments/assets/d28472e0-2bd9-4474-b267-e0374ec28676" width="300" >
> :wrench: Addressed an issue where the app would crash on the timetable screen when the font size on the device is increased.

- app-ios/App/App.xcodeproj/project.pbxproj
- app-ios/App/DroidKaigi2024App-Info.plist
- app-ios/App/InfoPlist.xcstrings
- close #839
- This PR adds localizations for the calendars usage description
- https://developer.apple.com/documentation/xcode/localizing-and-varying-text-with-a-string-catalog
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Localize calendars usage description

- app-ios/Sources/TimetableDetailFeature/TimetableDetailReducer.swift
- Responded to according to the following warning
- `Passing argument of non-sendable type 'TimetableDetailReducer.Action' into main actor-isolated context may introduce data races`
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Conform `Sendable` to TimetableDetailReducer.Action.

- app-ios/Sources/TimetableFeature/TimetableListView.swift
- close N/A
- This PR fixes the timetable list spacing to follow the design
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Fix timetable list spacing

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #852
- Can't tap the “Create Card” button when the keyboard is displayed. Therefore, the keyboard must be closed once, which is a poor user experience.
- 
Before | After
:--: | :--:
> Fixed “Create Card” button could not be tapped when the keyboard was displayed

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- None.
- Only the first line is displayed on CardScreen.
- It is not necessary to be able to enter two lines.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/6f889c70-d015-4119-b184-a4f4d94f4995" width="300" > | <video src="https://github.com/user-attachments/assets/e2b7800f-d046-4556-a0c2-ee7685c0f842" width="300" >
> :memo: Limit the number of lines that can be entered on the profile card edit screen to one line.

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/DroidKaigiKmpPreviewTester.kt
- gradle/libs.versions.toml
- close #830
- Update ComposablePreviewScanner 0.3.0
- Modify ComposePreviewTester
- I wrote this part based on that library, but it may not be entirely accurate
- [Compose Multiplatform Support](https://github.com/user-attachments/assets/b68b9c3f-1ac6-4c68-a12e-70595431ce50)
- [Diff ComposablePreviewScanner v0.2.0](https://github.com/sergio-sastre/ComposablePreviewScanner/pull/23/files)
- ComposePreviewTester pom files
- [0.1.3 pom file](https://jitpack.io/com/github/sergio-sastre/ComposablePreviewScanner/android/0.1.3/android-0.1.3.pom)
- [0.3.0 pom file](https://jitpack.io/com/github/sergio-sastre/ComposablePreviewScanner/android/0.3.0/android-0.3.0.pom)
Before | After
:--: | :--:
> Resolved ComposablePreviewScanner library dependency

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCard.kt
- None.
- I thought it would be useful to be able to swipe to flip cards on the profile card screen as well.
- https://github.com/DroidKaigi/conference-app-2024/blob/7799642fa0612ba250798675ccb51357768c8a44/feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapTab.kt#L49-L59
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/8289eac2-0d33-4a6a-bcfe-29883ae9de69" width="300" > | <video src="https://github.com/user-attachments/assets/a28180ae-e407-499f-8175-24d43cbd3b62" width="300" >
> :recycle: Cards can be flipped by swiping as in EventMap.

- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreenPresenter.kt
- None.
- It would be easier for users to understand that loading is in progress even when communication is slow if there is a loading indicator during loading.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/8f820a94-923f-472e-b0df-2ff4c1fc2e17" width="300" > | <video src="https://github.com/user-attachments/assets/1839c2ef-82fa-4fc0-ae3d-5872d1c1af6b" width="300" >
> :recycle: Add a loading display to the EventMap screen.

- app-ios/Sources/FavoriteFeature/FavoriteView.swift
- app-ios/Sources/SearchFeature/SearchView.swift
- app-ios/Sources/Theme/ColorAsset+Sendable.swift
- app-ios/Sources/Theme/FontConvertible+Sendable.swift
- The `@retroactive` attribute was necessary in Xcode 16, so it was applied using a macro branching process. However, the proposal [SE-0364](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0364-retroactive-conformance-warning.md#source-compatibility) describes a method that does not require macro branching and switches to that fully qualified method.
- Additionally, the `ColorAsset` and `FontConvertible` types did not need the `@retroactive` attribute, so the attribute and macros were removed.
- These types were created by SwiftGen in the `Theme` module, and the extensions were declared in the same `Theme` module.
- The `@retroactive` attribute is necessary when changes are made from external modules, so it was not meaningful in this context.
- …
> Remove unnecessary `retroactive` attribute

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #801 
- The edit button in ProfileCardScreen has a littele tap area. 
- The tap area  should be in the same size as the button for sharing one above.
- So, I try expanded the tap area.
- Please let me know if I am wrong below.
- I thought it would be better to use TextButton for the edit button than to make Text clickable, so I did so.
- Specify ButtonDefaults.buttonColors for colors, following the example of the Share button, etc.
- I've already confirmed that the ripple will look and feel good, similar to the share button.
- 
- The top and bottom position of the view has changed before and after the modification because of the added margin between the Share button and the... Please check if this is a problem.
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="" …
> Expand the tap area of the edit button In ProfileCardScreen

- app-ios-shared/src/iosTest/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiTest.kt
- None.
- The test code was broken due to the omission of an argument, so I fixed it.
- The test code was not modified when this was done.
- https://github.com/DroidKaigi/conference-app-2024/pull/836/files#diff-95ce4543f147fdb230f67281fa29911d85e7cfcb7571a32629c0c722dc547bbaR124
> :wrench: [IosComposeKaigiTest] A syntax error occurred due to insufficient arguments, so I fixed it.

- core/droidkaigiui/src/androidMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/SpeakerPainter.android.kt
- core/droidkaigiui/src/androidMain/res/drawable/icon_place_hoolder.xml
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/ImagePainter.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/SpeakerPainter.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemCard.kt
- core/droidkaigiui/src/iosMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/SpeakerPainter.ios.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- None.
- Currently, nothing is displayed on the icon until the speaker's icon has finished loading.
- So I am adding this because I think it would be better to have a placeholder displayed.
Before List | After List
:--: | :--:
<video src="https://github.com/user-attachments/assets/28f78da2-c214-4dfa-a3d0-fd90e644ff0a" width="300" > | <video src="https://github.com/user-attachments/assets/95621072-369a-4d03-a148-f82d51246705" width="300" >
Before Grid | After Grid
:--: | :--:
<video src="https://github.com/user-attachments/assets/f92519b0-5aff-42ec-a609-265537e57199" width="300" > | <video src="https://github.com/user-attachments/assets/3ad2c907-e1d0-4e5d-b807-5dd340243da6" width="300" >
Before Grid Pinch-In&Out | After Grid Pinch-In&Out
:--: | :--:
<video …
> :recycle: Placeholders are now displayed on the speaker icon of the Timetable Items.

- app-ios/Sources/TimetableFeature/TimetableGridCard.swift
- app-ios/Sources/TimetableFeature/TimetableListView.swift
None.（※ I found a solution and improved it.）
When displaying the Timeline screen as a grid, an unintended blank space occurred, causing the display of Jellyfish room to be cut off in the middle. We have made adjustments to resolve this situation.
- Adjust grid width about displaying timeline start.
- divide frame modifier maxWidth & height in TimetableGridCard.
- [Figma (about Timeline Grid)](https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=54849-10371&node-type=SECTION&t=gg56ROjbJ7k3uNLf-0)
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/3ed116df-8d57-4537-a20f-09f32298fc3d" width="300" > | <video src="https://github.com/user-attachments/assets/8541b9a9-35c1-4c67-8899-56693b1fbc45" width="300" …
> [iOS] Fix timeline grid unexpected margin.

- gradle.properties
- close N/A
- This PR removes a deprecated option in 'gradle.properties' to resolve the following build warning:
```
w: -memory-model and memoryModel switches are deprecated and will be removed in a future release.
```
- https://kotlinlang.org/docs/whatsnew1720.html#configuration-and-setup
Before | After
:--: | :--:
Before | After
:--: | :--:
> Remove deprecated option in configuration

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenPresenter.kt
- close #842
- Fixed a bug where `MIXED` was duplicated among Supported languages ​​items in the search filter
The `MIXED` value was duplicated during the mapping process in `sessions.languages` due to `toLang()` being applied, where `ENGLISH` or `JAPANESE` with `isInterpretationTarget` set to true caused this issue.
```kotlin
// SearchScreenPresenter.kt 96 line
val searchFilterLanguageUiState: SearchFilterUiState<Lang> by rememberUpdatedState(
SearchFilterUiState(
selectedItems = selectedLanguages,
selectableItems = sessions.languages.map { it.toLang() },
selectedValuesText = selectedLanguages.joinToString { it.tagName },
),
)
// TimetableLanguage.kt 15 line
fun toLang() = if (isInterpretationTarget) {
Lang.MIXED
} else {
Lang.entries.firstOrNull { it.tagName == langOfSpeaker.take(2) } …
```
> Fix duplicated language filter items

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
none
- The profile entry field is a singleLine, but it is possible to break lines using ImeAction. Therefore, ImeAction is set to Next or Done to prevent line breaks and allow smooth input.
- [Android developers - ImeAction](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/input/ImeAction)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/12941026-dfd1-4a63-81cd-8ec6f1bdd494" width="300" > | <video src="https://github.com/user-attachments/assets/a58bbde4-23aa-4a3f-8e76-a3bc84d2e69a" width="300" >
> In EditScreen, add keyboardOptions in InputFieldWithError

- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutContentColumn.kt
- close #728 
- the color of item's icons on AboutScreen differs from text color
- use same color for it
- 
Before | After
:--: | :--:
> Use same color for icon with text on AboutScreen items

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/EventMapScreenRobot.kt
- feature/eventmap/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreenTest.kt
- None.
- I searched the project for todoChecks and found todoCheks still in this location, so I added a test to address it.
> :wrench: Remove todoCheks from EventMapScreenTest.

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/component/ClickableLinkText.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #884
- Change the weight and color of links embedded in a `ClickableLinkText`, e.g. on the "About DroidKaigi" screen
**Figma**
Before | After
:--: | :--:
> Update style of links inside a ClickableLinkText to match the design

- app-ios/Sources/EventKitClient/EventKitClient.swift
- app-ios/Sources/EventKitClient/LiveKey.swift
- in progress #431
- This addresses the issue where making EKEventStore a static let triggers the following warning:
- ```Static property eventStore is not concurrency-safe because it is not either conforming to Sendable or isolated to a global actor; this is an error in Swift 6.```
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fix: concurrency strict warnings in EventKitClient

- app-ios/.swiftlint.yml
- close N/A
- This PR fixes invalid included paths in the configuration to run SwiftLint properly:
```
Error: No lintable files found at paths: ''
```
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Run SwiftLint properly

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sessions/FakeSessionsApiClient.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/TimetableAsset.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableItemDetailScreenRobot.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailContent.kt
- None.
- The asset section will not be displayed until after DroidKaigi2024 has ended.
- However, there is currently no test for that part.
- So, I added a test to check that it displays properly after the event is over.
- In the process, I realized that the asset section would not be displayed unless both the slides and the video were present, so I also fixed that part.
> :recycle: [TimetableItemDetailScreenTest] Since there is a lack of VRT for assets, we have added VRT so that they can be tested.

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/ProfileCardScreenRobot.kt
- feature/profilecard/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenTest.kt
- feature/profilecard/src/commonMain/composeResources/values-ja/strings.xml
- feature/profilecard/src/commonMain/composeResources/values/strings.xml
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenPresenter.kt
- close #800
- Add URL check if input value is valid format or not
- valid URL example:
- https://example.com/foobar/hogefuga
- http://www.example.com
- example.com/foobar
- contains punycode like https://xn--wgv71a119e.jp/
- invalid URL example:
- invalid protocol 
- ttps://example.com
- missing top level domain
- https://example/foobar
- invalid characters
- https://#$%.com
- Add some test to check regular expression works as expected
- Change keyboard type of link to Uri
- Rename error string variables.
Before | After
:--: | :--:
> Add URL validation

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpKtorfitPlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpPlugin.kt
- close #772
- Moved task for KspTaskNative to KmpPlugin
- Remove task for KotlinNativeLink from KmpKtorfitPlugin because it doesn't affect build any more (I don't know why though).
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Move notCompatibleWithConfigurationCache.

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
none
- It is quite detailed...
- The schedule has icons and text surrounded by a Row, but the height of the icons is fixed, so if the font size on the device is changed, the height will not match and the alignment will be shifted.
Title | Before | After
small font | <img src="https://github.com/user-attachments/assets/1d4ca9ac-0564-4718-a6bc-f382425d3cf8" width="300" /> | <img src="https://github.com/user-attachments/assets/fe0df80a-6dcb-4304-8dcd-f8fd6d336ae0" width="300" />
medium font | <img src="https://github.com/user-attachments/assets/7f8c67ca-f5fd-4177-a8d8-9254a8e95edf" width="300" /> | <img src="https://github.com/user-attachments/assets/8debd736-9466-492a-bfba-7d58aa82cc54" width="300" />
large font | <img …
> In TimetableGridItem, Schedule icon align is misaligned when changing the font size on the device

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- close #894
- The number of rows of the Speaker name in the GridItem of the timetable was different from that in the figma, so it was clarified so that ellipsis is always done in one line.
- 
Before | After | figma
Before | After
:--: | :--:
> feat: add ellipsis and maxLines state explicitly to Speaker text

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/TimetableItem.kt
- close #783
- Add month and date at sharing text.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Add month and date at sharing text.

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeNavRail.kt
none
- The appearance of BottomNavigation and NavRail on devices that do not support Blur and those that do is so different that we have made changes to make them look a little more similar.
- The alpha value is set to a value that I feel is just right for me to touch.
orientation | Before | After | SupportBlur
:--: | :--: | :--: | :--:
vertical | <img src="https://github.com/user-attachments/assets/f3e6dc76-3382-4531-b716-0565cc7b7f1c" width="300" /> | <img src="https://github.com/user-attachments/assets/329318c9-5b21-41d6-9220-a51051059fd8" width="300" /> | <img src="https://github.com/user-attachments/assets/599eb51b-d2ce-4753-8922-7afd60040bbf" width="300" />
horizontal | <img src="https://github.com/user-attachments/assets/ac9663ef-6c99-475d-9ece-62a1784d43c6" width="300" /> | <img …
> Changed color of BottomNavigation and NavRail when Blur is not supported

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #898
- Add the text style `titleMedium`.
- 
Before | After | Figma
> :bug: fix text style in edit screen.

- app-ios/Sources/CommonComponents/Timetable/CircularUserIcon.swift
- app-ios/Sources/StaffFeature/StaffLabel.swift
- app-ios/Sources/TimetableFeature/TimetableGridCard.swift
- close N/A
- This PR adds gray borders to user icons
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Add borders to user icons

- core/droidkaigiui/src/androidMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/SpeakerPainter.android.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/ImagePainter.kt
- close #912
- Every time you scroll, a new ImageRequest instance was created using LocalContext.current.
- As a result, rememberAsyncImagePainter would create a new Painter each time, causing flickering when scrolling.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/f523f9f1-6a5e-49d7-916f-6fc8ef4069cc" width="300" > | <img src="https://github.com/user-attachments/assets/d30a232b-10af-47d3-8242-f23d7af2e516" width="300" >
> :wrench: The problem of flickering icons has been addressed by caching ImageRequests.

- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/AboutScreenRobot.kt
- feature/about/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/about/AboutScreenTest.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/AboutScreen.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutOthers.kt
- None.
- As there is already someone in charge of testing the footer, I did not implement that part.
- https://github.com/DroidKaigi/conference-app-2024/issues/670
> :recycle: Since the About screen test has not been implemented, it has been implemented except where the Issue manager is located.

- feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
- feature/sessions/src/commonMain/composeResources/values/strings.xml
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenPresenter.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/EmptySearchResultBody.kt
- close #798
- Added a message to the strings file to be displayed when there are no results and no search input.
- Modified to change the display message based on whether the search text is empty or not.
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=58871-8744&t=WGCdhOBgDfcbOcP9-4
Before | After
:--: | :--:
When there is input
> Modify to change the display message based on whether the search text is empty or not

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- close #920
- I have made it so that the focus is cleared at the following times.
1. When you tap anywhere on the screen.
2. When you perform the Done action on the last item.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/1ded325f-7c34-4746-9a61-1adc08dba4be" width="300" > | <video src="https://github.com/user-attachments/assets/823dd9a5-efae-4a32-a594-1f40c1a6b0e2" width="300" >
> :wrench: We have made some modifications to the profile card screen so that focus is handled appropriately.

- app-android/src/main/AndroidManifest.xml
- app-android/src/main/res/values/themes.xml
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidGradleDsl.kt
- Title says it all.
- The oss-licenses-plugin has disabled Edge-to-Edge because it cannot control insets padding.
- https://developer.android.com/about/versions/15/behavior-changes-all
- https://developer.android.com/about/versions/15/behavior-changes-15
Before | After
:--: | :--:
No difference
Before | After
:--: | :--:
> Bump target sdk version to 35

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
The TextField has a maximum of 1 line, but long text will wrap and scroll vertically.
If you want to apply a single line, it is more natural to have a horizontally scrollable input field.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/6946e9f9-0fa5-4d6e-8112-43f7d08636a7" width="300" > | <video src="https://github.com/user-attachments/assets/ee2e2dc1-23a8-49c0-9222-6942901a231a" width="300" >
> [Profile Card]Fixed profile input scroll direction

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- close #902 
- This PR fixes the timelineText component to ensure it is limited to a maximum of three lines while preserving the existing layout.
- 
Before | After
:--: | :--:
> fix: timetableGridItem title maxLine3 while keeping the existing layout

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableGrid.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableSheet.kt
- close #914
- In Timetable Screen,  remove bottom empty space due to `DateTab` offset.
- Replace **Column and offset** with **Box and Padding**.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/547da23c-8def-4563-b867-ce461712bf69" width="300" > | <video src="https://github.com/user-attachments/assets/fd22ca7d-d5f2-4fae-aeab-51cc43bc3fe5" width="300" >
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/2aaf0623-45bc-4d16-9441-f2e57d36838b" width="300" > | <video src="https://github.com/user-attachments/assets/b3151287-37b3-4153-ab2d-8d14d1b1e512" width="300" >
> Fix bottom space from DayTab offsets in Timetable Screen

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/CaptureableCardBack.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/CaptureableCardFront.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/ShareableCard.kt
- None.
- Using the CompositionLocalProvider, we fixed the Density and FontScale for FlipCards used for shooting.
- Until this was fixed, the text size would fluctuate as reported in the issue and as shown in the screenshot, and in some cases the cards would be displayed squashed.
- With this fix, the appearance should now be consistent on all devices.
- https://github.com/DroidKaigi/conference-app-2024/issues/890#issuecomment-2322770976
Before Portrait Minimum SmallPhone | After Portrait Minimum SmallPhone
:--: | :--:
Before Landscape Minimum SmallPhone | After Landscape Minimum SmallPhone
:--: | :--:
Before Portrait Max SmallPhone | After Portrait Max SmallPhone
:--: | :--:
Before Landscape Max SmallPhone | After Landscape Max SmallPhone
:--: | :--:
---
Before Portrait Minimum Pixel 7 …
> :wrench: This addresses the case where the image of the ProfileCard used for sharing on SNS etc. is corrupted in some cases.

- core/designsystem/build.gradle.kts
- feature/about/build.gradle.kts
- feature/contributors/build.gradle.kts
- feature/eventmap/build.gradle.kts
- feature/favorites/build.gradle.kts
- feature/main/build.gradle.kts
- feature/profilecard/build.gradle.kts
- feature/sessions/build.gradle.kts
- feature/settings/build.gradle.kts
- feature/sponsors/build.gradle.kts
- feature/staff/build.gradle.kts
- close None
Compiler warned "This declaration needs opt-in." in some build.gradle.kts files because they used `roborazzi.generateComposePreviewRobolectricTests.packages` without `OptIn(ExperimentalRoborazziApi::class)`.  
Output logs were so annoying that I prevented them all.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Prevents opt-in needed warning

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailHeadline.kt
- None.
- By using FlowRow instead of Row, the language switching switch is now displayed with automatic wrapping.
- Until this was implemented, the language switch could not be pressed on some devices with low resolution, as shown in the attached video.
- https://developer.android.com/develop/ui/compose/layouts/flow?hl=ja
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/a074db36-9657-404a-838a-dd0471789c50" width="300" > | <video src="https://github.com/user-attachments/assets/a3ba142c-e1ad-49c2-8553-07f414347fc9" width="300" >
> :wrench: We have made modifications so that the language switching switch can be pressed even on small devices with low resolution.

- feature/settings/src/commonMain/kotlin/io/github/droidkaigi/confsched/settings/section/SettingsAccessibility.kt
- None.
- Because the height of the text was a fixed value, when the font size was increased, the text was cut off and became unreadable.
- This makes it _less accessible_.
Before | After
:--: | :--:
> :wrench: [SettingsScreen]The accessibility text was cut off, so I fixed it.

- core/droidkaigiui/src/iosMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/OrientationSensorManager.ios.kt
- close #960
- Everything is written in the Issue.
- Even if you take a Before/After video using ADB or xcrun, it's meaningless because you can't see how the device is being moved in your hands after all.
- Also, I couldn't take a video because there was a risk that the video would include images of my living environment if I used the camera. 🙇 
- I'm sorry that it takes a long time to build the actual device, but if you try installing the main one and this branch one, you'll see that the movement when tilting the device has been corrected and is consistent between Android and iOS.
- Please merge after you have seen the fix on the actual device. 🙏
> :wrench: [IosOrientationSensorManager] Reverse the pitch value to match the left-hand coordinate system.

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/component/AutoSizeText.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/AnimatedLargeTopAppBar.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/AnimatedMediumTopAppBar.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/AnimatedTextTopAppBar.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableScreenRobot.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/utils/Matchers.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- close #757
- Introduce `AutoSizeText`, a component that automatically finds the correct size to fit a text into a box
- The maximum font size is defined by the `style` of the text, but it will shrink if necessary
- It uses a binary search to find the biggest size that fits in a given number of lines
- Apply it to all titles in every top app bar of the app
- The custom app bar of `TimetableScreen`
- `AnimatedTextTopAppBar` (fix for the main tabs on the home screen)
- `AnimatedMediumTopAppBar` (fix for contributor, sponsor, staff, settings screens)
Tabs (Large Font) | Tabs (Normal Font) | Contributor Screen
<video src="https://github.com/user-attachments/assets/37fd5583-1ea1-42f7-8382-0ff4f128804a" width="300" > | <video …
> Introduce auto sizing for all app bar title components

- app-ios/Sources/TimetableFeature/TimetableGridCard.swift
- close N/A
- This PR updates the layout of the timetable grid cells with multiple speakers to match the Android app implementation:
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Update layout of timetable grid cells with multiple speakers

- app-ios/Sources/ContributorFeature/KmpPresenterContributorView.swift
- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreen.kt
- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreenPresenter.kt
- None.
- I modified the UIState so that it can display a loading screen.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/67601f22-f08e-4ac4-9dce-e4868d568913" width="300" > | <video src="https://github.com/user-attachments/assets/b892655f-b8f0-4f70-a08a-1c816e6e2be8" width="300" >
> :recycle: [iOS & Android ContributorsScreen]Added loading indicator since it is missing.

- feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridTab.kt
- None.
- The Preview method names are inconsistent, with the name “Preview” appearing in either the prefix or suffix.
- If possible, we would like to unify the name so that it is attached only to either the suffix or the prefix.
> :memo: The method with the prefix “Preview” has been renamed so that the suffix has “Preview”.

- app-android/src/main/res/values-v35/themes.xml
- app-android/src/main/res/values/themes.xml
- close #967
- Lint complains about the usage of `android:windowOptOutEdgeToEdgeEnforcement`, a new property introduced in Android 15
- Introduce a resource folder for v35-specific files and move this declaration into `themes.xml` in that folder
- https://qiita.com/Nabe1216/items/cea8f7043f57bfd20bca
Output of `./gradlew :app-android:lintDevDebug`
|Before|After|
|---|---|
|<img width="350" alt="Screenshot 2024-09-05 at 18 40 34" src="https://github.com/user-attachments/assets/c7751333-c841-49d7-bd11-a528665fd4ec">|<img width="350" alt="Screenshot 2024-09-05 at 18 43 23" src="https://github.com/user-attachments/assets/5d28943a-bed6-4f9a-a30b-5e1acc87f0fc">|
> Move v35-only theme declaration into the correct themes.xml

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/convention/AndroidFeaturePlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidGradleDsl.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidKotlinPlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpAndroidPlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpComposePlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpIosPlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpKtorfitPlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpPlugin.kt
- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KotlinGradleDsl.kt
- close #933 
- Raplace `kotlinOptions` to `compilerOptions`
- Replace `buildDir` to `layout.buildDirectory`
- Change reciever of `kotlinOptions` from `TestedExtension` to `Project`
- TestedExtension somehow causes `Extension of type 'KotlinAndroidProjectExtension' does not exist.`
- Move dsl function `kotlinOptions`  from `KotlinGradleDsl.kt` to `AndroidGradleDsl.kt` because it now focuses only android target
- Add libraryAndroidOptions
- kotlinAndroidOptions can be used only `org.jetbrains.kotlin.android` is applied, otherwise ` Extension of type 'KotlinAndroidProjectExtension' does not exist` happens
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> fix deprecated compiler options

- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteSheet.kt
- close #958 
- Fixed the tint of the icon in the EmptyView of the Favorites screen
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55521-44698&t=U0Y9WYLKYOmTCVrL-4
Before | After
:--: | :--:
Before | After
:--: | :--:
> Fixed the color of the icon in empty favorite sheet

- app-ios/Tests/ContributorFeatureTests/ContributorFeatureTests.swift
- app-ios/Tests/TimetableDetailFeatureTests/TimetableDetailTests.swift
- To improve the accuracy and comprehensiveness of the tests.
- Existing practices have not been tested for success or failure.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Improve usage of store.receive in multiple tests

- app-ios/Package.swift
- app-ios/Sources/SponsorFeature/SponsorReducer.swift
- app-ios/Sources/SponsorFeature/SponsorView.swift
- app-ios/Tests/SponsorFeatureTests/SponsorFeatureTests.swift
- Add logic to open sponsor page
- Fix behavior when tapping sponsor button 
- Currently, when the button is tapped, a square background is displayed.
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/9aab29d1-870c-4387-b963-19627970e9e6" width="300" >
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/fa6e2ebb-30d9-447b-a005-739a854fb914" width="300" > | <video src="https://github.com/user-attachments/assets/1e833a2d-d0a6-48e4-be35-11988ab6af0b" width="300" >
> Fix sponsor view bugs

- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/TimetableRoom.kt
fix floor information
- I fixed a problem where the floor information for session rooms wasn't showing up correctly.
- Flamingo (B1F) --> Flamingo (1F)
- Giraffe (B1F) --> Giraffe (1F)
- 
| Before | After |
| :--: | :--: | 
| ![Screenshot_20240906_114318](https://github.com/user-attachments/assets/825fa7dc-59f9-472b-a9e0-a17dd07e4d6b) | ![Screenshot_20240906_113327](https://github.com/user-attachments/assets/4f6dfe0e-478d-411a-985b-591cea7dd001) |
Before | After
:--: | :--:
> Fix the floor information for session rooms 

- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableGrid.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableSheet.kt
- close #955
- We have tried to make the necessary corrections, but there is no prospect of being able to make the corrections by the deadline.
- Unfortunately, we have no choice but to revert. 😞 
- @takahirom @kktaro We apologize for not being able to provide you with the ideal revision response. 🙇 
- https://github.com/DroidKaigi/conference-app-2024/pull/919
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/4a5f1a9f-b73c-46a2-ac36-36c388f0ef5a" width="300" > | <video src="https://github.com/user-attachments/assets/62832fc0-2b6e-464c-9203-decf13a05e33" width="300" >
> :wrench: Revert Fix bottom space from DayTab offsets in Timetable Screen.

- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/ContributorsRepository.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/EventMapRepository.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/SponsorsRepository.kt
- core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/StaffRepository.kt
- close #954
- This PR improves suspend functions and fixes an app crash when a network issue occurs
- https://github.com/DroidKaigi/conference-app-2022/pull/894
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] Fix app crash when network issue occurs

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/CustomSemanticsProperties.kt
- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemCard.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/SearchScreenRobot.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/utils/Matchers.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/SearchList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableSheet.kt
- close #931
- Hoist the additional tag composable upwards, so that TimetableList and SearchScreen can use different content
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/56fa8dc9-1d87-4739-a75f-f9b89050728c" width="300" > | <video src="https://github.com/user-attachments/assets/ab9b829d-37ce-4599-9d7f-7cef3d9daa6c" width="300" >
> Align TimetableItemTag content for SearchScreen with Figma

- core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/component/ClickableLinkText.kt
- None.
- I made some of the processing I implemented last year easier to understand.
- https://github.com/DroidKaigi/conference-app-2023/pull/706
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/07c558de-f8a8-46fa-842d-f52768858598" width="300" > | <video src="https://github.com/user-attachments/assets/b06c519b-fcfc-4913-82bb-174ea8923f99" width="300" >
> :wrench: [ClickableLinkText] Processing has been simplified.

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemTag.kt
- feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableItemDetailHeadline.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/SearchList.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/section/TimetableSheet.kt
- close #930
- There are now two variants of this component
- The first requires color+icon and is used for the colored 'room' tags
- Any other usage in the app uses the same grayish color and no icon, so expose that as a second variant
Note the subtle change for the gray tags.
Before | After
:--: | :--:
Incorrect outline color | 
Before | After
:--: | :--:
Missing icon, incorrect outline color |
Before | After
:--: | :--:
Incorrect outline color | 
Before | After
:--: | :--:
Incorrect outline color |
> Refactor TimetableItemTag API to use consistent colors

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpPlugin.kt
- close #1008
- Suppresses warnings about "actual" and "expect" class declarations
- https://kotlinlang.org/docs/multiplatform-expect-actual.html#expected-and-actual-classes
Before | After
:--: | :--:
> Suppresses KMP "actual" and "expect" class warnings

- feature/profilecard/src/commonMain/composeResources/values-ja/strings.xml
- feature/profilecard/src/commonMain/composeResources/values/strings.xml
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCard.kt
- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCardBack.kt
- Improved accessibility(TalkBack) on the ProfileCardScreen
- 
※ The TalkBack speech output can be found at the bottom of each screenshot
Description |Before | After
:--: | :--:| :--:
Added a description for the delete button |<img src="https://github.com/user-attachments/assets/0ce638ef-9046-455b-b840-a8365747def2" width="300" /> | <img src="https://github.com/user-attachments/assets/ef70d95d-ca6b-4d00-8284-538f4b58671c" width="300" />
Added selection state and description for the theme |<img src="https://github.com/user-attachments/assets/4a0c10e9-ffba-4d41-aad9-213866c33166" width="300" /> | <img src="https://github.com/user-attachments/assets/94eac540-45d2-4444-b6a3-713bfd0b7884" width="300" />
Added selection state and description for the theme |<img …
> Improved accessibility on the ProfileCardScreen

- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/component/ContributorsCountItem.kt
- close #1001
- Changed `targetValue` from `remember` to `rememberSaveable` 
- I thought this problem was caused by recomposition by scrolling. 
- To avoid this I used `rememberSaveable`.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/5f2fabf4-9416-4e0e-aa6d-480137502c8f" width="300" > | <video src="https://github.com/user-attachments/assets/47832be0-6ca4-45b9-b7fa-9b6e15c425ca" width="300" >
> Prevent TotalContributor animation from recomposition on scroll

- core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemCard.kt
- feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutContentColumn.kt
- feature/contributors/src/commonMain/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt
- feature/settings/src/commonMain/kotlin/io/github/droidkaigi/confsched/settings/SettingsScreen.kt
- feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreen.kt
- feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt
- close #1016
- When the same item in the BottomNavigation is tapped, lifecycleOwner.lifecycle.currentState becomes DESTROYED and becomes impossible to tap.
- If you scroll, it will return to RESUMED and become tapable again.
- Because the number of days remaining until DroidKaigi is limited, there is no time to spare to deal with this phenomenon in a fundamental way.
- For now, it would be best to remove it.
<video src="https://github.com/user-attachments/assets/c8800ef5-8b5c-459b-a64e-5ee850ae88e8" width="300">
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/a495820e-06c7-4c8f-9a67-2de71c0cd0e7" width="300" > | <video src="https://github.com/user-attachments/assets/358627b2-4582-4fdd-a454-4ce24fd84787" width="300" >
> :wastebasket: DropUnlessResumed is causing navigation issues on AboutScreen, so DropUnlessResumed is removed.

- app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
- close #1014
- https://github.com/DroidKaigi/conference-app-2024/blob/82bcd5c65a2d7bafed797eaed98c1cdbc99c3822/app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt#L139-L142
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/99914c88-c535-4b87-9c75-9b467ff4270e" width="300" > | <video src="https://github.com/user-attachments/assets/8b2ce731-af00-4dd3-9112-bf9a36bd9eee" width="300" >
> :recycle: [IosComposeKaigiApp.kt] Modified to use SharedTransitionLayout in the same way as KaigiApp.kt.

- feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt
- close #1022 
- I adjusted the position of the loading spinner in StaffScreen with ContributorScreen
- https://github.com/DroidKaigi/conference-app-2024/issues/1022
Before | After | ContributorScreen
> Fix the position of the loading spinner in StaffScreen

- core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sessions/FakeSessionsApiClient.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
- core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/TimetableItemDetailScreenRobot.kt
- feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreenTest.kt
- feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreen.kt
- close #1024
- A UI has been added to display messages on the TimetableItemDetailScreen when messages exist.
- We have added VRT to check that the added UI is functioning.
Before | After
:--: | :--:
> :sparkles: [TimetableItemDetailScreen] I added a UI to display a message in the event of cancellation.

- app-ios/Sources/CommonComponents/Timetable/TimetableCard.swift
- close #987 
- Fix bug that canceled special session's message is not showed
- 
Before | After
:--: | :--:
> Fix bug that canceled special session's message is not showed

- build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/KmpComposePlugin.kt
- build.gradle.kts
- gradle/libs.versions.toml
- close #995
- define composeFoundation in version catalog
- implementation composeFoundation in KmpComposePlugin androidMain dependencies
- remove resolutionStrategy
-
> implementation foundation:1.8.0-alpha01 instead of resolutionStrategy

- app-ios/Sources/App/RootView.swift
- support Button Shapes accessibility to tabItems (fix tab design bug)
- This fix also expands the tap area of the tab buttons, making them easier to tap.
- I changed the width of the entire tab to be determined by padding relative to the device's width. If need to make the width larger for design purposes, can adjust the padding. (Of course, I can also revert the width setting to a fixed value.
I made the width based on padding relative to the device's width because I felt that it looks a bit nicer, as the tab width becomes wider and more responsive on larger devices. However, this is a personal preference and may vary from person to person.)
Before | After
:--: | :--:
> [iOS] support Button Shapes accessibility to tabItems (fix tab design bug)

- app-ios/Sources/ContributorFeature/ContributorReducer.swift
- app-ios/Sources/ContributorFeature/ContributorView.swift
- app-ios/Sources/SponsorFeature/SponsorReducer.swift
- app-ios/Sources/SponsorFeature/SponsorView.swift
- app-ios/Sources/StaffFeature/StaffReducer.swift
- app-ios/Sources/StaffFeature/StaffView.swift
- app-ios/Tests/StaffFeatureTests/StaffFeatureTests.swift
- Conform ViewAction Protocol from TCA v1.7
- StaffReducer
- SponsorReducer
- ContributorReducer
- https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/migratingto1.7/
Before | After
:--: | :--:
Before | After
:--: | :--:
> Conform ViewAction Protocol of TCA

- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
- feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeNavRail.kt
- On devices with large screens, the NavRail was positioned in the upper left corner.
- On foldable devices, the size of the NavRail seemed small.
- NavRail height changed to 420 dp.
- NavRail centered vertically on the left side of the screen.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> Change NavRail position to center on large screen

- feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
- [Link](https://github.com/DroidKaigi/conference-app-2024/pull/971)
- Clear icon placed for profile screen's EditText(clear function not yet implemented)
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [ProfileCardScreen] Design enhancement

- app-ios/Sources/AboutFeature/AboutView.swift
1. include the padding areas, expanding the tap area to the full width.
2. fix spacing（Because VStack has default spacing, need to set spacing: 0）
3. commonalize spacing and ButtonStyle
and minor fixes(add opacity animation, add ButtonStyle & LabelStyle extension, remove unnecessary frame settings, etc)
Before | After
:--: | :--:
Before | After
:--: | :--:
I enabled the "Button Shapes" for testing purposes and confirmed that it causes the design to break.
If there is no existing issue for this, it might be a good idea to create one.
> [iOS] refactor AboutView: improve button tap area & fix spacing & commonalize style

- app-ios/Sources/TimetableFeature/TimetableReducer.swift
- app-ios/Sources/TimetableFeature/TimetableView.swift
- close #1033
- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
> [iOS] fix ios timetable list/grid always reset on any action

- app-ios/Sources/ContributorFeature/ContributorsCountItem.swift
- close #1001
- This PR prevents the contributors counting animation from firing on scroll
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/d381db0d-b5f1-4937-bcdd-80fed490eee0" width="300" > | <video src="https://github.com/user-attachments/assets/880cd7bb-4bdc-480b-9f8e-21aab69f9f55" width="300" >
> [iOS] Prevent contributors counting animation from firing on scroll

- app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
- close https://github.com/DroidKaigi/conference-app-2024/issues/672
Changed code order of navigateToNativeApp to avoid potential confusion. 👌🏼
> Refactor code order of navigateToNativeApp
