app-ios/Sources/EventMapFeature/Model/FloorMap.swift
app-ios/Sources/TimetableFeature/TimetableReducer.swift

Fixed build to succeed in ios
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fixed build to succeed in ios

---

.github/workflows/unit-test.yml

- For creating screenshots for each commit. It is needed for comparison workflow.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Remove concurrency restriction for unit test ci

---

README.md

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Add a guide to check Composable Preview

---

app-ios/Tests/EventMapFeatureTests/EventMapTests.swift
app-ios/Tests/FavoriteFeatureTests/FavoriteTests.swift

- Added event map feature tests in iOS
- Fix build error in favorite feature tests
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Added event map feature tests in iOS

---

README.md

- I fixed the class name of Robot
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix architecture image

---

core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sessions/DefaultSessionsApiClient.kt
core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/TimetableRoom.kt

- None.
- Just as the title says.
- <img src="https://github.com/user-attachments/assets/6cc782b6-9775-4cf1-8fa1-9a731bcf0040" width="300" />
- https://medium.com/droidkaigi/droidkaigi-2024-tickets-35a26ee7c45a

:wrench: Corrected the comment to reflect that the first day of DroidKaigi 2024 is Workshop Day.

---

.github/workflows/remove-waiting-label.yml
.github/workflows/save-pr-number-for-removing-waiting-label.yml 

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Add waiting label workflow

---

.github/workflows/remove-waiting-label.yml

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix permissions

---

.github/workflows/remove-waiting-label.yml

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Add run_id to remove-waiting-label.yml

---

.github/workflows/remove-waiting-label.yml

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix to use dawidd6/action-download-artifact

---

.github/workflows/save-pr-number-for-removing-waiting-label.yml

…-label
- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Add pull_request_review_comment to save-pr-number-for-removing-waiting-label

---

app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt

- close #219
- Share link is displaye when tap share link button in TimetableItemDetailScreen.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/8cb4c60d-769a-499f-88a5-eeff39c5108f" width="300" > | <video src="https://github.com/user-attachments/assets/6ec2880f-fe3e-4ca0-a9cc-123c113cc103" width="300" >

share session detail

---

feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapItem.kt

- close #346 
- Added background to Preview. Used Surface.

Add BackGround MapItem

---

feature/contributors/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreenTest.kt

- close #349
- Add check methods in ContributorsScreenRobot.
- Implement checks in ContributorsScreenTest.
- 
unrelated to UI
unrelated to UI

add contributors screen test checks

---

core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/SponsorsScreenRobot.kt
feature/sponsors/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreenTest.kt

- close #350 
- Add check methods in SponsorsScreenRobot.
- Implement checks in SponsorsScreenTest.
-

Fix SponsorsScreenTest checks

---

app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/FavoritesScreenRobot.kt
feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
feature/eventmap/src/iosMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapViewController.kt
feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt

- (PR only)
The topBar design was not matching the Figma specs, so I’ve corrected it by switching to `AnimatedTextTopAppBar`.
This change might affect issue #338, so I'll make sure to leave a comment on that issue once this PR is merged.
- Event Map
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=56051-33221&t=AtrYOKed4lDBiu3T-1
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=56051-33622&t=AtrYOKed4lDBiu3T-1
- Favorite
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55499-43411&t=AtrYOKed4lDBiu3T-1
- https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55499-43432&t=AtrYOKed4lDBiu3T-1
Before | After
:--: | :--:
<video …

Update topBar with AnimatedTextTopAppBar

---

core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/NetworkService.kt

- close #380
- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Remove reified to fix ios crash

---

app-ios/Package.swift
app-ios/Sources/CommonComponents/Timetable/RoomTag.swift
app-ios/Sources/CommonComponents/Timetable/TimetableCard.swift
app-ios/Sources/EventMapFeature/EventItem.swift
app-ios/Sources/EventMapFeature/EventMapReducer.swift
app-ios/Sources/EventMapFeature/EventMapView.swift
app-ios/Sources/EventMapFeature/Resources/Localizable.xcstrings
app-ios/Sources/KMPClient/LiveKey.swift
app-ios/Sources/Model/Extension/RoomType+Extension.swift
app-ios/Sources/Model/Extension/TimetableRoom+Extension.swift
app-ios/Sources/TimetableDetailFeature/Component/SessionDescriptionView.swift
app-ios/Sources/TimetableDetailFeature/TimetableDetailView.swift
core/data/src/iosMain/kotlin/io/github/droidkaigi/confsched/data/DataModule.kt

- close #313 
- Added event list into EventMapView
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55725-8925&t=ksxzQYBOQy0QhDQQ-4
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/0586117c-d1de-4bc8-88cd-319581f0b555" width="300" >

Add event list into EventMapView

---

core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/StaffScreenRobot.kt
feature/staff/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/staff/StaffScreenTest.kt
feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt

- close #351
- Added a basic test to check whether a StaffItem is present or not.
- None.

:recycle: Add StaffScreenTest checks.

---

feature/profilecard/build.gradle.kts
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/PhotoPickButton.kt
gradle/libs.versions.toml

- implement photo picker(by peekaboo)
- show image
- implement a button to delete image
when select non-square image, show error dialog
https://github.com/user-attachments/assets/41ff1a7e-59a2-4882-8341-f0e41b8cd697
select image
https://github.com/user-attachments/assets/b52cec61-5df1-45f0-91b0-c83a3175c6a7

ProfileCard: implement photo picker

---

.github/workflows/ios-assign-reviewers.yml

- Added github action to auto assign reviewers when creating pull request for iOS.

Added auto assign reviewers action for iOS

---

app-ios/Sources/App/RootReducer.swift
app-ios/Sources/App/RootView.swift
app-ios/Sources/CommonComponents/SelectionChips.swift
app-ios/Sources/TimetableDetailFeature/TimetableDetailReducer.swift
app-ios/Sources/TimetableDetailFeature/TimetableDetailView.swift
app-ios/Sources/TimetableFeature/Resource/Localizable.xcstrings
app-ios/Sources/TimetableFeature/TimetableListView.swift
app-ios/Sources/TimetableFeature/TimetableReducer.swift
app-ios/Tests/TimetableDetailFeatureTests/TimetableDetailTests.swift

- Added logic to favorite session into TimetableListView and TimetableDetailView
- Mini refacror
Before | After
:--: | :--:
<video src="" width="300" > | <video src="https://github.com/user-attachments/assets/6d3d2d7e-27d1-45d4-9d40-cbe5bb60dc45" width="300" >

Added logic to favorite session into TimetableListView and TimetableDetailView

---

build.gradle.kts

- close https://github.com/DroidKaigi/conference-app-2024/issues/439
- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix robolectric timeout issue by compose.foundation alpha

---

feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt

- close #375
- Wrap with captureWithChecks tests (TimetableScreenTest.kt)

Wrap with captureWithChecks

---

app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/KmpEntryPoint.kt
build-logic/src/main/kotlin/io/github/droidkaigi/confsched/convention/KmpFeaturePlugin.kt
build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/AndroidRoborazziPlugin.kt
build-logic/src/main/kotlin/io/github/droidkaigi/confsched/primitive/ComposeInvestigatorPlugin.kt
feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreenPresenter.kt

- no issue
- Lint results remove unused imports.

🧹 Remove unused import

---

feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCard.kt

- close #460 
- Moved FlipCard.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

update: Move FlipCard to component package Resolves #460

---

.github/workflows/ios-assign-reviewers.yml
.github/workflows/labeler.yml
.github/workflows/save-pr-number-for-ios-assign-reviewers.yml

- Fix workflow to assign reviewers for ios pull request
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix workflow to assign reviewers for ios

---

feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/section/SponsorsList.kt

- From reading the code it looks like the items you want to display are different.
- I think this code is selected platinumSponsors by mistake.
- If not, please close this PR 🙏 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix item in Supporters section

---

core/common/src/commonMain/kotlin/io/github/droidkaigi/confsched/compose/EventEmitter.kt
core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/ProfileCardScreenTheme.kt
core/designsystem/src/commonMain/kotlin/io/github/droidkaigi/confsched/designsystem/theme/RoomTheme.kt
feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailPresenter.kt
feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt

- no issue
- Remove parameter type definitions that can be removed

🧹 Lint, Remove explicit type arguments

---

app-ios/README.md

- nothing
- `TiemtableDetailFeature` ->  `TimetableDetailFeature`
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix typo in README

---

feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/section/AboutDroidKaigiDetail.kt

- close #462 
- renaming "maxAboutHeaderOffsetDp" to "MaxAboutHeaderOffsetDp"
- none

#462 refactor: Change constant variable naming "maxAboutHeaderOffsetDp" to "MaxAboutHeaderOffsetDp"

---

core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/SponsorsScreenRobot.kt
feature/sponsors/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreenTest.kt
feature/sponsors/src/commonMain/composeResources/values-ja/strings.xml
feature/sponsors/src/commonMain/composeResources/values/strings.xml
feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreen.kt
feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/component/SponsorItem.kt
feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/section/SponsorsList.kt

- #464 
- There are other screens with similar missing checks, so we have not yet closed them.
- Modified to check if the elements of individual items are visible.

:recycle: Enhanced SponsorsScreen testing. 

---

app-ios/Package.swift
app-ios/Sources/KMPClient/Client.swift
app-ios/Sources/KMPClient/LiveKey.swift
app-ios/Sources/Model/Entity/Staff.swift
app-ios/Sources/StaffFeature/StaffReducer.swift
app-ios/Sources/StaffFeature/StaffView.swift
app-ios/Tests/StaffFeatureTests/StaffFeatureTests.swift

- Patch for a concurrency warning with Swift6 in StaffReducer

Fix: concurrency strict warning in StaffReducer

---

app-ios/Sources/ContributorFeature/ContributorListItemView.swift
app-ios/Sources/ContributorFeature/ContributorReducer.swift
app-ios/Sources/ContributorFeature/KmpPresenterContributorView.swift
app-ios/Sources/KMPClient/Client.swift
app-ios/Sources/KMPClient/LiveKey.swift
app-ios/Sources/Model/Entity/Contributor.swift
app-ios/Tests/ContributorFeatureTests/ContributorFeatureTests.swift

- Patch for a concurrency warning with Swift6 in ContributorReducer

Fix: concurrency strict warning in ContributorReducer

---

app-ios/Sources/KMPClient/Client.swift
app-ios/Sources/KMPClient/LiveKey.swift
app-ios/Sources/Model/Entity/Sponsor.swift
app-ios/Sources/SponsorFeature/SponsorReducer.swift
app-ios/Sources/SponsorFeature/SponsorView.swift
app-ios/Tests/SponsorFeatureTests/SponsorFeatureTests.swift

- Patch for a concurrency warning with Swift6 in SponsorReducer

Fix: concurrency strict warning in SponsorReducer

---

app-android/src/main/java/io/github/droidkaigi/confsched/KaigiApp.kt
feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreen.kt
feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/navigation/EventMapDestination.kt
feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt

- close #411
- Fix to displayed screen and selected MainScreenTab may be different when OS back gesture.
- none
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/7770717f-3d96-481f-b73d-cbd96e270774" width="300" > | <video src="https://github.com/user-attachments/assets/1fb2e6c5-fe7c-4fbd-9fb3-92274e4c9f29" width="300" >

Fix to displayed screen and selected MainScreenTab may be different when OS back gesture.

---

core/testing/src/main/java/io/github/droidkaigi/confsched/testing/RobolectricDescribeSpecParameterBuilder.kt

- close #558 
- I make run function deprecated. And add doIt function.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

depracated run function

---

feature/profilecard/build.gradle.kts
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCard.kt
gradle/libs.versions.toml

- close #622
- Add [qrcode-kotlin](https://github.com/g0dkar/qrcode-kotlin) as QR  code generator library.
- Show generated QR code.
- https://github.com/g0dkar/qrcode-kotlin
Before | After
:--: | :--:
None | <img src="https://github.com/user-attachments/assets/895120d7-9d03-4e7b-ab00-35aad2ab81f4" width="300" />
Before | After
:--: | :--:

Qr code generate

---

.github/workflows/ios-assign-reviewers.yml

- Fix iOS auto reviewer assign workflow
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Fix iOS auto reviewer assign workflow

---

app-ios/Sources/AboutFeature/Localizable.xcstrings
app-ios/Sources/SearchFeature/Resources/Localizable.xcstrings

- https://github.com/DroidKaigi/conference-app-2024/issues/432
Modify Localizable.xcstrings below:
- modify `AboutFeature/Localizable.xcstrings` (NavigationTitle)
- modify `SearchFeature/Resources/Localizable.xcstrings` (SearchChip)
（If you notice anything else I've overlooked, I'd appreciate it if you could leave a comment 🙏 ）
About Screen | Search Chips
:--: | :--:

English translation support for About Screen Title & Search Chips

---

feature/eventmap/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/eventmap/EventMapScreenTest.kt

:wrench: [EventMapScreen] Replace the run method, which is now deprecated, with the do It method. 

---

feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/SearchScreenTest.kt

:wrench: [SearchScreen] Replace the run method, which is now deprecated, with the do It method.

---

feature/contributors/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/contributors/ContributorsScreenTest.kt

:wrench: [ContributorsScreen] Replace the run method, which is now deprecated, with the do It method. 

---

feature/staff/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/staff/StaffScreenTest.kt

:wrench: [StaffScreen] Replace the run method, which is now deprecated, with the do It method. 

---

feature/sponsors/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sponsors/SponsorsScreenTest.kt

:wrench: [SponsorsScreen] Replace the run method, which is now deprecated, with the do It method. 

---

feature/about/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/about/AboutScreenTest.kt

:wrench: [AboutScreen] Replace the run method, which is now deprecated, with the do It method.

---

feature/favorites/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenTest.kt

:wrench: [FavoritesScreen] Replace the run method, which is now deprecated, with the do It method.

---

feature/profilecard/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenTest.kt

:wrench: [ProfileCardScreen] Replace the run method, which is now deprecated, with the do It method.

---

feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableItemDetailScreenTest.kt

:wrench: [TimetableItemDetailScreen] Replace the run method, which is now deprecated, with the do It method.

---

feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt

:wrench: [TimetableScreen] Replace the run method, which is now deprecated, with the do It method.

---

app-ios/Sources/CommonComponents/Timetable/RoomTag.swift
app-ios/Sources/CommonComponents/Timetable/RoomTypeShape.swift
app-ios/Sources/CommonComponents/Timetable/TimetableCard.swift
app-ios/Sources/EventMapFeature/EventItem.swift
app-ios/Sources/Model/Entity/MultiLangText.swift
app-ios/Sources/Model/Entity/RoomTheme.swift
app-ios/Sources/Model/Entity/RoomType.swift
app-ios/Sources/Model/Extension/RoomType+Extension.swift
app-ios/Sources/Model/Extension/TimetableRoom+Extension.swift
app-ios/Sources/TimetableDetailFeature/TimetableDetailView.swift
app-ios/Sources/TimetableFeature/TimetableGridCard.swift

- In progress https://github.com/DroidKaigi/conference-app-2024/issues/431
- Prepare for EventMap, Timetable, TimetableDetail Reducers Swift6 warning support.
- Separated RoomTag.shape
- Add wrapped structures for KMP class

Refactoring RoomTag

---

app-ios-shared/build.gradle.kts
app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
core/data/src/androidMain/kotlin/io/github/droidkaigi/confsched/data/about/AboutRepositoryModule.kt
core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/about/DefaultAboutRepository.kt
core/data/src/iosMain/kotlin/io/github/droidkaigi/confsched/data/DataModule.kt

- 
https://github.com/user-attachments/assets/cd435d87-2f94-4e69-9314-c33fdad2f97b
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Add navigation destination for iOS

---

app-android/src/test/java/io/github/droidkaigi/confsched/KaigiAppTest.kt
core/testing/src/main/java/io/github/droidkaigi/confsched/testing/RobolectricDescribeSpecParameterBuilder.kt
feature/sessions/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreenTest.kt

:wrench: Replace the run method completely with the doIt method.

---

feature/eventmap/src/commonMain/kotlin/io/github/droidkaigi/confsched/eventmap/component/EventMapTab.kt

- None.
- Perhaps it would be more intuitive to reverse the process.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/36b4d6f9-c882-466d-b23d-6481ee1d5b92" width="300" > | <video src="https://github.com/user-attachments/assets/1ada21e6-3f8b-4ba2-87e7-5c977584f3b3" width="300" >

:wrench: [EventMapScreen] Reversed the process when swiping a finger.

---

feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCard.kt

- close #730 
- Changed qr code to square
- https://github.com/g0dkar/qrcode-kotlin?tab=readme-ov-file#usage
Before | After
:--: | :--:

Change QRrcode to square

---

app-android/src/main/res/xml/locales_config.xml
gradle/libs.versions.toml

- 
- ⌘ + Opt + L
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Refactoring: Reformat locales_config.xml & libs.versions.toml

---

app-android/build.gradle.kts

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Bump up version to 1.0.0(2)

---

core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sponsors/SponsorsApiClient.kt

- I apologize for overlooking in the code review that we were using last year's sponsor API.
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Update to reflect 2024 sponsors

---

feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt

- close #594
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/e35738b7-6a5f-4778-b1dc-43387e1c7dbf" width="300" > | <video src="https://github.com/user-attachments/assets/0598d8f9-cb75-4092-9e33-ed3c5d4cdd19" width="300" >

:wrench: [ProfileCardScreen] Touch anywhere on the screen to close the keyboard.

---

app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt

- close #726
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/1ce9e525-1af2-4178-959a-08339f22e448" width="300" > | <video src="https://github.com/user-attachments/assets/4b8eacf4-337d-4a06-b2ba-f5dd17ea6534" width="300" >

:wrench: [Compose Multiplatform] Fill in the missing branch of routeToTab used in BottomNaviation and modify it to work the same way as in Android.

---

.github/workflows/ios-build-test.yml

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Upload XCFrameworks in CI

---

app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiApp.kt
app-ios-shared/src/commonMain/kotlin/io/github/droidkaigi/confsched/shared/share/ShareNavigator.kt

- None.
- We are currently unable to confirm that it works on the actual device, but we assume that it works because the code is almost identical to the code for the share function with images.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/f26382e7-e3d8-410d-8caf-a69c98dc65da" width="300" > | <video src="https://github.com/user-attachments/assets/c559b5e8-797c-4b2a-b1ca-b6438444792d" width="300" >

:sparkles: Implemented session sharing functionality from Compose Multiplatform as well.

---

app-ios/Sources/ProfileCardFeature/Input/ProfileCardInputImage.swift
app-ios/Sources/SponsorFeature/SponsorView.swift
app-ios/Sources/StaffFeature/StaffView.swift
app-ios/Sources/TimetableFeature/TimetableListView.swift

- close N/A
- States should be private
- https://developer.apple.com/documentation/swiftui/state
Before | After
:--: | :--:
Before | After
:--: | :--:

[iOS] Declare states as private

---

app-ios/Sources/CommonComponents/Timetable/TimetableCard.swift
app-ios/Sources/TimetableDetailFeature/TimetableDetailView.swift

- close #756
- This PR adds haptic feedback to the favorite buttons
- https://developer.apple.com/documentation/swiftui/view/sensoryfeedback(_:trigger:condition:)
Before | After
:--: | :--:
Before | After
:--: | :--:

[iOS] Play haptic feedback when favoriting

---

feature/main/src/commonMain/composeResources/values-ja/strings.xml
feature/main/src/commonMain/composeResources/values/strings.xml
feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeBottomNavigation.kt
feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/section/GlassLikeNavRail.kt
feature/sessions/src/commonMain/composeResources/values-ja/strings.xml
feature/sessions/src/commonMain/composeResources/values/strings.xml
feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/TimetableScreen.kt

- Improved talkback description.
- Timetable's TopAppBar action button.
- NavigationBar and NavigationRail item.
- 
Before | After
:--: | :--:
No effect on UI.
Before | After
:--: | :--:

Improve root components accessibility

---

app-ios/Sources/ProfileCardFeature/Input/ProfileCardInputReducer.swift

- Responded to according to the following warning 
- `Immutable value 'internalAction' was never used; consider replacing with '_' or removing it`
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Erase unused variable declarations

---

feature/eventmap/build.gradle.kts
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt

- None.
- There was an unnecessary implementation in Gradle, so I deleted it.

:wastebasket: [EventMapScreen] Since it is implemented in KmpFeaturePlugin, there is no need to implement it here, so we will remove it.

---

feature/main/src/commonMain/kotlin/io/github/droidkaigi/confsched/main/MainScreen.kt
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreen.kt

:wastebasket: [MainScreen] IconRepresentation is not used, so it has been deleted.

---

app-ios/Sources/AboutFeature/AboutView.swift

- `AboutView` does not require the `LicenseList` target
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Remove unnecessary import

---

core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/MiniRobots.kt
core/testing/src/main/java/io/github/droidkaigi/confsched/testing/robot/ProfileCardScreenRobot.kt
feature/profilecard/src/androidUnitTest/kotlin/io/github/droidkaigi/confsched/profilecard/ProfileCardScreenTest.kt
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/TiltEffectModifier.kt
feature/profilecard/src/commonMain/kotlin/io/github/droidkaigi/confsched/profilecard/component/FlipCard.kt

- None.
- Inspired by @shunm-999 's implementation of #750, I tried making the cards tilt when the device is tilted.
- https://github.com/DroidKaigi/conference-app-2024/pull/750
<video src="https://github.com/user-attachments/assets/3b063306-4ef4-4ac2-add8-e7411b40a54d" width="300" >

:sparkles: [Proposal] The profile card will tilt in accordance with the tilt of the device.

---

feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreen.kt
feature/staff/src/commonMain/kotlin/io/github/droidkaigi/confsched/staff/StaffScreenPresenter.kt

- None.
- I modified the UIState so that it can display a loading screen.
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/294f99f5-08d5-4c4f-aa14-f15df6aa8f4b" width="300" > | <video src="https://github.com/user-attachments/assets/20044f8b-656a-4995-bdb2-81de8d657b81" width="300" >

:recycle: [StaffScreen]Added loading indicator since it is missing.

---

app-ios/Package.swift

- Remove unnecessary dependencies described in Package.swift 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Remove unnecessary dependencies listed in Package.swift

---

app-ios/Sources/ContributorFeature/SwiftUIContributorView.swift
app-ios/Sources/TimetableFeature/TimetableListView.swift

- close N/A
- This PR fixes invalid access control levels
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

[iOS] Fix invalid ACLs

---

app-ios-shared/src/iosTest/kotlin/io/github/droidkaigi/confsched/shared/IosComposeKaigiTest.kt

- close #964
- The test code was broken due to the omission of an argument, so I fixed it.
- https://github.com/DroidKaigi/conference-app-2024/pull/881

:wrench: [IosComposeKaigiTest] [2nd time] A syntax error occurred due to insufficient arguments, so I fixed it.

---

app-ios/Tests/SponsorFeatureTests/SponsorFeatureTests.swift
app-ios/Tests/StaffFeatureTests/StaffFeatureTests.swift

- Rename test method from default name in `SponsorFeatureTests` and `StaffFeatureTests`
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Rename test method from default name

---

core/data/src/commonMain/kotlin/io/github/droidkaigi/confsched/data/sessions/DefaultSessionsApiClient.kt
core/droidkaigiui/src/commonMain/kotlin/io/github/droidkaigi/confsched/droidkaigiui/component/TimetableItemCard.kt
core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/Timetable.kt
core/model/src/commonMain/kotlin/io/github/droidkaigi/confsched/model/TimetableItem.kt
feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt

- close #987 
- Fix to show message and icon for special session
- Change info icon on grid screen based on Figma
I think I should add test code but I understand this is high priority.
So I put off it until later.
- 
Before | After
:--: | :--:
|<img src="https://github.com/user-attachments/assets/f47d12b8-db0a-4e27-9a20-abbb292000b4" width="300" />|<img src="https://github.com/user-attachments/assets/e4e6ac9c-6ab1-4eea-bda9-367a83ccd9a8" width="300" />
|<img src="https://github.com/user-attachments/assets/412999fe-5ed7-4620-8aab-158ec2ebf870" width="300">|<img src="https://github.com/user-attachments/assets/617e47eb-68c1-4862-bbda-8a0a9d63a0b0" width="300">
Before | After
:--: | :--:

Fix to show message for special session

---

feature/about/src/commonMain/kotlin/io/github/droidkaigi/confsched/about/component/AboutFooterLinksIcon.kt

none
- I thought it was not good for the user experience that nothing changes when you try to press LinkIcons on the AboutScreen, so I add animation size to Icon so that it becomes a little smaller when you press it.
- [Android developers - InteractionSource](https://developer.android.com/reference/kotlin/androidx/compose/foundation/interaction/InteractionSource)
Before | After
:--: | :--:
<video src="https://github.com/user-attachments/assets/8c220785-5aac-4453-b78d-1823e069295e" width="300" > | <video src="https://github.com/user-attachments/assets/11d1fc74-e422-4266-a49d-7b3c71f2a04c" width="300" >

In AboutScreen, LinksIcon so that you know you are operating when you press it

---

app-android/build.gradle.kts

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Update to 1.4.0(8)

---

app-android/build.gradle.kts

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Update app version to 1.5.0(9)

---

app-ios/Sources/EventMapFeature/Resources/Localizable.xcstrings

- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

[iOS] fix localize

---

app-android/build.gradle.kts
feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreen.kt
feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/FavoritesScreenPresenter.kt
feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteList.kt
feature/favorites/src/commonMain/kotlin/io/github/droidkaigi/confsched/favorites/section/FavoriteSheet.kt

- close #1039
- 
- 
Before | After
:--: | :--:
Before | After
:--: | :--:

Add day to TimeSlot

---

build-logic/build.gradle.kts
build-logic/settings.gradle
settings.gradle.kts

This change applies the tips introduced in @RyuNen344's presentation at DroidKaigi 2024.
- https://2024.droidkaigi.jp/timetable/690464/
- https://speakerdeck.com/ryunen344/sapuraitiengong-ji-nibei-eru?slide=38
By filtering dependencies retrieved from the Google repository, this prevents unnecessary requests to the Google repository, which is expected to improve build speed.
I have verified that the repository sources for each artifact remain unchanged, ensuring there are no regressions.
```bash
rm -rf ~/.gradle
./gradlew -m -i --refresh-dependencies assembleDevDebug > dependencies.log
grep -v 'missing' dependencies.log | grep -o 'https://[^ ]*.pom' | sort | uniq > downloaded.log
diff downloaded-before.log downloaded-after.log  # No difference
```
The following requests, previously …

Restrict artifact downloads from Google repository to specific ones 
